apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: predictmarket-api
  namespace: predictmarket
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: predictmarket-api
