// Code generated by "twill generate". DO NOT EDIT.
//go:build !ignoreTwillGen

package main

import (
	"context"
	"github.com/nxsky/twill"
	"github.com/nxsky/twill/runtime/codegen"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:      "github.com/nxsky/twill/Main",
		Iface:     reflect.TypeOf((*twill.Main)(nil)).Elem(),
		Impl:      reflect.TypeOf(application{}),
		Listeners: []string{"public"},
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return main_local_stub{impl: impl.(twill.Main), tracer: tracer}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any { return main_client_stub{stub: stub} },
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return main_server_stub{impl: impl.(twill.Main), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return main_reflect_stub{caller: caller}
		},
		RefData: "⟦c022c72e:wEaVeReDgE:github.com/nxsky/twill/Main→github.com/afun-game/predictmarket-saas/internal/merchant/Service⟧\n⟦61891720:wEaVeReDgE:github.com/nxsky/twill/Main→github.com/afun-game/predictmarket-saas/internal/event/Service⟧\n⟦cf22030e:wEaVeReDgE:github.com/nxsky/twill/Main→github.com/afun-game/predictmarket-saas/internal/eventsync/Service⟧\n⟦ca19aa2d:wEaVeReDgE:github.com/nxsky/twill/Main→github.com/afun-game/predictmarket-saas/internal/market/Service⟧\n⟦3f7b0441:wEaVeReDgE:github.com/nxsky/twill/Main→github.com/afun-game/predictmarket-saas/internal/marketmaker/Service⟧\n⟦c93e46df:wEaVeReDgE:github.com/nxsky/twill/Main→github.com/afun-game/predictmarket-saas/internal/order/Service⟧\n⟦f8d5d4f4:wEaVeReDgE:github.com/nxsky/twill/Main→github.com/afun-game/predictmarket-saas/internal/reconciliation/Service⟧\n⟦cbff6a12:wEaVeReDgE:github.com/nxsky/twill/Main→github.com/afun-game/predictmarket-saas/internal/settlementmonitor/Service⟧\n⟦ff649f74:wEaVeReDgE:github.com/nxsky/twill/Main→github.com/afun-game/predictmarket-saas/internal/settlement/Service⟧\n⟦7f087ed0:wEaVeReDgE:github.com/nxsky/twill/Main→github.com/afun-game/predictmarket-saas/internal/settlementworker/Service⟧\n⟦2275cd8a:wEaVeReDgE:github.com/nxsky/twill/Main→github.com/afun-game/predictmarket-saas/internal/wallet/Service⟧\n⟦5320200c:wEaVeReDgE:github.com/nxsky/twill/Main→github.com/afun-game/predictmarket-saas/internal/currency/Service⟧\n⟦0ba4785b:wEaVeReDgE:github.com/nxsky/twill/Main→github.com/afun-game/predictmarket-saas/internal/sports/Service⟧\n⟦92c1c8cf:wEaVeReDgE:github.com/nxsky/twill/Main→github.com/afun-game/predictmarket-saas/internal/analytics/Service⟧\n⟦2c040526:wEaVeRlIsTeNeRs:github.com/nxsky/twill/Main→public⟧\n",
	})
}

// twill.InstanceOf checks.
var _ twill.InstanceOf[twill.Main] = (*application)(nil)

// twill.Router checks.
var _ twill.Unrouted = (*application)(nil)

// Local stub implementations.

type main_local_stub struct {
	impl   twill.Main
	tracer trace.Tracer
}

// Check that main_local_stub implements the twill.Main interface.
var _ twill.Main = (*main_local_stub)(nil)

// Client stub implementations.

type main_client_stub struct {
	stub codegen.Stub
}

// Check that main_client_stub implements the twill.Main interface.
var _ twill.Main = (*main_client_stub)(nil)

// Note that "twill generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][24]struct{}](`

ERROR: You generated this file with 'twill generate' v0.24.7 (codegen
version v0.24.0). The generated code is incompatible with the version of the
github.com/nxsky/twill module that you're using. The twill module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/nxsky/twill

We recommend updating the twill module and the 'twill generate' command by
running the following.

    go get github.com/nxsky/twill@latest
    go install github.com/nxsky/twill/cmd/twill@latest

Then, re-run 'twill generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/Twill/twill/issues.

`)

// Server stub implementations.

type main_server_stub struct {
	impl    twill.Main
	addLoad func(key uint64, load float64)
}

// Check that main_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*main_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s main_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	default:
		return nil
	}
}

// Reflect stub implementations.

type main_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that main_reflect_stub implements the twill.Main interface.
var _ twill.Main = (*main_reflect_stub)(nil)
