// Code generated by "twill generate". DO NOT EDIT.
//go:build !ignoreTwillGen

package market

import (
	"context"
	"errors"
	"fmt"
	"github.com/afun-game/predictmarket-saas/pkg/types"
	"github.com/nxsky/twill"
	"github.com/nxsky/twill/runtime/codegen"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "github.com/afun-game/predictmarket-saas/internal/market/Service",
		Iface: reflect.TypeOf((*Service)(nil)).Elem(),
		Impl:  reflect.TypeOf(implementation{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return service_local_stub{impl: impl.(Service), tracer: tracer, addLiquidityMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/market/Service", Method: "AddLiquidity", Remote: false, Generated: true}), createMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/market/Service", Method: "Create", Remote: false, Generated: true}), getMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/market/Service", Method: "Get", Remote: false, Generated: true}), getOrderBookMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/market/Service", Method: "GetOrderBook", Remote: false, Generated: true}), listMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/market/Service", Method: "List", Remote: false, Generated: true}), updateStatusMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/market/Service", Method: "UpdateStatus", Remote: false, Generated: true})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return service_client_stub{stub: stub, addLiquidityMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/market/Service", Method: "AddLiquidity", Remote: true, Generated: true}), createMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/market/Service", Method: "Create", Remote: true, Generated: true}), getMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/market/Service", Method: "Get", Remote: true, Generated: true}), getOrderBookMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/market/Service", Method: "GetOrderBook", Remote: true, Generated: true}), listMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/market/Service", Method: "List", Remote: true, Generated: true}), updateStatusMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/market/Service", Method: "UpdateStatus", Remote: true, Generated: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return service_server_stub{impl: impl.(Service), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return service_reflect_stub{caller: caller}
		},
		RefData: "",
	})
}

// twill.InstanceOf checks.
var _ twill.InstanceOf[Service] = (*implementation)(nil)

// twill.Router checks.
var _ twill.Unrouted = (*implementation)(nil)

// Local stub implementations.

type service_local_stub struct {
	impl                Service
	tracer              trace.Tracer
	addLiquidityMetrics *codegen.MethodMetrics
	createMetrics       *codegen.MethodMetrics
	getMetrics          *codegen.MethodMetrics
	getOrderBookMetrics *codegen.MethodMetrics
	listMetrics         *codegen.MethodMetrics
	updateStatusMetrics *codegen.MethodMetrics
}

// Check that service_local_stub implements the Service interface.
var _ Service = (*service_local_stub)(nil)

func (s service_local_stub) AddLiquidity(ctx context.Context, a0 string, a1 float64) (err error) {
	// Update metrics.
	begin := s.addLiquidityMetrics.Begin()
	defer func() { s.addLiquidityMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "market.Service.AddLiquidity", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.AddLiquidity(ctx, a0, a1)
}

func (s service_local_stub) Create(ctx context.Context, a0 *CreateRequest) (r0 *types.Market, err error) {
	// Update metrics.
	begin := s.createMetrics.Begin()
	defer func() { s.createMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "market.Service.Create", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Create(ctx, a0)
}

func (s service_local_stub) Get(ctx context.Context, a0 string) (r0 *types.Market, err error) {
	// Update metrics.
	begin := s.getMetrics.Begin()
	defer func() { s.getMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "market.Service.Get", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Get(ctx, a0)
}

func (s service_local_stub) GetOrderBook(ctx context.Context, a0 string) (r0 *OrderBook, err error) {
	// Update metrics.
	begin := s.getOrderBookMetrics.Begin()
	defer func() { s.getOrderBookMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "market.Service.GetOrderBook", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetOrderBook(ctx, a0)
}

func (s service_local_stub) List(ctx context.Context, a0 *ListFilters) (r0 []*types.Market, r1 int, err error) {
	// Update metrics.
	begin := s.listMetrics.Begin()
	defer func() { s.listMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "market.Service.List", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.List(ctx, a0)
}

func (s service_local_stub) UpdateStatus(ctx context.Context, a0 string, a1 string) (err error) {
	// Update metrics.
	begin := s.updateStatusMetrics.Begin()
	defer func() { s.updateStatusMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "market.Service.UpdateStatus", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.UpdateStatus(ctx, a0, a1)
}

// Client stub implementations.

type service_client_stub struct {
	stub                codegen.Stub
	addLiquidityMetrics *codegen.MethodMetrics
	createMetrics       *codegen.MethodMetrics
	getMetrics          *codegen.MethodMetrics
	getOrderBookMetrics *codegen.MethodMetrics
	listMetrics         *codegen.MethodMetrics
	updateStatusMetrics *codegen.MethodMetrics
}

// Check that service_client_stub implements the Service interface.
var _ Service = (*service_client_stub)(nil)

func (s service_client_stub) AddLiquidity(ctx context.Context, a0 string, a1 float64) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.addLiquidityMetrics.Begin()
	defer func() { s.addLiquidityMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "market.Service.AddLiquidity", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += 8
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	enc.Float64(a1)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

func (s service_client_stub) Create(ctx context.Context, a0 *CreateRequest) (r0 *types.Market, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.createMetrics.Begin()
	defer func() { s.createMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "market.Service.Create", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	servicetwill_enc_ptr_CreateRequest_9fc92d57(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 1, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = servicetwill_dec_ptr_Market_c7aa54b9(dec)
	err = dec.Error()
	return
}

func (s service_client_stub) Get(ctx context.Context, a0 string) (r0 *types.Market, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getMetrics.Begin()
	defer func() { s.getMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "market.Service.Get", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 2, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = servicetwill_dec_ptr_Market_c7aa54b9(dec)
	err = dec.Error()
	return
}

func (s service_client_stub) GetOrderBook(ctx context.Context, a0 string) (r0 *OrderBook, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getOrderBookMetrics.Begin()
	defer func() { s.getOrderBookMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "market.Service.GetOrderBook", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 3, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = servicetwill_dec_ptr_OrderBook_d9452d61(dec)
	err = dec.Error()
	return
}

func (s service_client_stub) List(ctx context.Context, a0 *ListFilters) (r0 []*types.Market, r1 int, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.listMetrics.Begin()
	defer func() { s.listMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "market.Service.List", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += servicetwill_size_ptr_ListFilters_b6166968(a0)
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	servicetwill_enc_ptr_ListFilters_b6166968(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 4, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = servicetwill_dec_slice_ptr_Market_0ccb1e02(dec)
	r1 = dec.Int()
	err = dec.Error()
	return
}

func (s service_client_stub) UpdateStatus(ctx context.Context, a0 string, a1 string) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.updateStatusMetrics.Begin()
	defer func() { s.updateStatusMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "market.Service.UpdateStatus", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += (4 + len(a1))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	enc.String(a1)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 5, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

// Note that "twill generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][24]struct{}](`

ERROR: You generated this file with 'twill generate' (devel) (codegen
version v0.24.0). The generated code is incompatible with the version of the
github.com/nxsky/twill module that you're using. The twill module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/nxsky/twill

We recommend updating the twill module and the 'twill generate' command by
running the following.

    go get github.com/nxsky/twill@latest
    go install github.com/nxsky/twill/cmd/twill@latest

Then, re-run 'twill generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/Twill/twill/issues.

`)

// Server stub implementations.

type service_server_stub struct {
	impl    Service
	addLoad func(key uint64, load float64)
}

// Check that service_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*service_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s service_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "AddLiquidity":
		return s.addLiquidity
	case "Create":
		return s.create
	case "Get":
		return s.get
	case "GetOrderBook":
		return s.getOrderBook
	case "List":
		return s.list
	case "UpdateStatus":
		return s.updateStatus
	default:
		return nil
	}
}

func (s service_server_stub) addLiquidity(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 float64
	a1 = dec.Float64()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.AddLiquidity(ctx, a0, a1)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) create(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *CreateRequest
	a0 = servicetwill_dec_ptr_CreateRequest_9fc92d57(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.Create(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	servicetwill_enc_ptr_Market_c7aa54b9(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) get(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.Get(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	servicetwill_enc_ptr_Market_c7aa54b9(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) getOrderBook(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetOrderBook(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	servicetwill_enc_ptr_OrderBook_d9452d61(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) list(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *ListFilters
	a0 = servicetwill_dec_ptr_ListFilters_b6166968(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, r1, appErr := s.impl.List(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	servicetwill_enc_slice_ptr_Market_0ccb1e02(enc, r0)
	enc.Int(r1)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) updateStatus(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 string
	a1 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.UpdateStatus(ctx, a0, a1)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

// Reflect stub implementations.

type service_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that service_reflect_stub implements the Service interface.
var _ Service = (*service_reflect_stub)(nil)

func (s service_reflect_stub) AddLiquidity(ctx context.Context, a0 string, a1 float64) (err error) {
	err = s.caller("AddLiquidity", ctx, []any{a0, a1}, []any{})
	return
}

func (s service_reflect_stub) Create(ctx context.Context, a0 *CreateRequest) (r0 *types.Market, err error) {
	err = s.caller("Create", ctx, []any{a0}, []any{&r0})
	return
}

func (s service_reflect_stub) Get(ctx context.Context, a0 string) (r0 *types.Market, err error) {
	err = s.caller("Get", ctx, []any{a0}, []any{&r0})
	return
}

func (s service_reflect_stub) GetOrderBook(ctx context.Context, a0 string) (r0 *OrderBook, err error) {
	err = s.caller("GetOrderBook", ctx, []any{a0}, []any{&r0})
	return
}

func (s service_reflect_stub) List(ctx context.Context, a0 *ListFilters) (r0 []*types.Market, r1 int, err error) {
	err = s.caller("List", ctx, []any{a0}, []any{&r0, &r1})
	return
}

func (s service_reflect_stub) UpdateStatus(ctx context.Context, a0 string, a1 string) (err error) {
	err = s.caller("UpdateStatus", ctx, []any{a0, a1}, []any{})
	return
}

// AutoMarshal implementations.

var _ codegen.AutoMarshal = (*CreateRequest)(nil)

type __is_CreateRequest[T ~struct {
	twill.AutoMarshal
	MerchantID    string   "json:\"merchant_id\""
	EventID       string   "json:\"event_id\""
	Type          string   "json:\"type\""
	Question      string   "json:\"question\""
	Options       []string "json:\"options\""
	LiquidityPool float64  "json:\"liquidity_pool\""
}] struct{}

var _ __is_CreateRequest[CreateRequest]

func (x *CreateRequest) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("CreateRequest.WeaverMarshal: nil receiver"))
	}
	enc.String(x.MerchantID)
	enc.String(x.EventID)
	enc.String(x.Type)
	enc.String(x.Question)
	servicetwill_enc_slice_string_4af10117(enc, x.Options)
	enc.Float64(x.LiquidityPool)
}

func (x *CreateRequest) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("CreateRequest.WeaverUnmarshal: nil receiver"))
	}
	x.MerchantID = dec.String()
	x.EventID = dec.String()
	x.Type = dec.String()
	x.Question = dec.String()
	x.Options = servicetwill_dec_slice_string_4af10117(dec)
	x.LiquidityPool = dec.Float64()
}

func servicetwill_enc_slice_string_4af10117(enc *codegen.Encoder, arg []string) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for i := 0; i < len(arg); i++ {
		enc.String(arg[i])
	}
}

func servicetwill_dec_slice_string_4af10117(dec *codegen.Decoder) []string {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make([]string, n)
	for i := 0; i < n; i++ {
		res[i] = dec.String()
	}
	return res
}

var _ codegen.AutoMarshal = (*ListFilters)(nil)

type __is_ListFilters[T ~struct {
	twill.AutoMarshal
	MerchantID string "json:\"merchant_id,omitempty\""
	EventID    string "json:\"event_id,omitempty\""
	Status     string "json:\"status,omitempty\""
	Page       int    "json:\"page,omitempty\""
	Limit      int    "json:\"limit,omitempty\""
}] struct{}

var _ __is_ListFilters[ListFilters]

func (x *ListFilters) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("ListFilters.WeaverMarshal: nil receiver"))
	}
	enc.String(x.MerchantID)
	enc.String(x.EventID)
	enc.String(x.Status)
	enc.Int(x.Page)
	enc.Int(x.Limit)
}

func (x *ListFilters) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("ListFilters.WeaverUnmarshal: nil receiver"))
	}
	x.MerchantID = dec.String()
	x.EventID = dec.String()
	x.Status = dec.String()
	x.Page = dec.Int()
	x.Limit = dec.Int()
}

var _ codegen.AutoMarshal = (*OrderBook)(nil)

type __is_OrderBook[T ~struct {
	twill.AutoMarshal
	MarketID string           "json:\"market_id\""
	Bids     []OrderBookEntry "json:\"bids\""
	Asks     []OrderBookEntry "json:\"asks\""
}] struct{}

var _ __is_OrderBook[OrderBook]

func (x *OrderBook) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("OrderBook.WeaverMarshal: nil receiver"))
	}
	enc.String(x.MarketID)
	servicetwill_enc_slice_OrderBookEntry_97b5cf1b(enc, x.Bids)
	servicetwill_enc_slice_OrderBookEntry_97b5cf1b(enc, x.Asks)
}

func (x *OrderBook) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("OrderBook.WeaverUnmarshal: nil receiver"))
	}
	x.MarketID = dec.String()
	x.Bids = servicetwill_dec_slice_OrderBookEntry_97b5cf1b(dec)
	x.Asks = servicetwill_dec_slice_OrderBookEntry_97b5cf1b(dec)
}

func servicetwill_enc_slice_OrderBookEntry_97b5cf1b(enc *codegen.Encoder, arg []OrderBookEntry) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for i := 0; i < len(arg); i++ {
		(arg[i]).WeaverMarshal(enc)
	}
}

func servicetwill_dec_slice_OrderBookEntry_97b5cf1b(dec *codegen.Decoder) []OrderBookEntry {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make([]OrderBookEntry, n)
	for i := 0; i < n; i++ {
		(&res[i]).WeaverUnmarshal(dec)
	}
	return res
}

var _ codegen.AutoMarshal = (*OrderBookEntry)(nil)

type __is_OrderBookEntry[T ~struct {
	twill.AutoMarshal
	Option string  "json:\"option\""
	Price  float64 "json:\"price\""
	Amount float64 "json:\"amount\""
	Orders int     "json:\"orders\""
}] struct{}

var _ __is_OrderBookEntry[OrderBookEntry]

func (x *OrderBookEntry) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("OrderBookEntry.WeaverMarshal: nil receiver"))
	}
	enc.String(x.Option)
	enc.Float64(x.Price)
	enc.Float64(x.Amount)
	enc.Int(x.Orders)
}

func (x *OrderBookEntry) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("OrderBookEntry.WeaverUnmarshal: nil receiver"))
	}
	x.Option = dec.String()
	x.Price = dec.Float64()
	x.Amount = dec.Float64()
	x.Orders = dec.Int()
}

// Encoding/decoding implementations.

func servicetwill_enc_ptr_CreateRequest_9fc92d57(enc *codegen.Encoder, arg *CreateRequest) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func servicetwill_dec_ptr_CreateRequest_9fc92d57(dec *codegen.Decoder) *CreateRequest {
	if !dec.Bool() {
		return nil
	}
	var res CreateRequest
	(&res).WeaverUnmarshal(dec)
	return &res
}

func servicetwill_enc_ptr_Market_c7aa54b9(enc *codegen.Encoder, arg *types.Market) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func servicetwill_dec_ptr_Market_c7aa54b9(dec *codegen.Decoder) *types.Market {
	if !dec.Bool() {
		return nil
	}
	var res types.Market
	(&res).WeaverUnmarshal(dec)
	return &res
}

func servicetwill_enc_ptr_OrderBook_d9452d61(enc *codegen.Encoder, arg *OrderBook) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func servicetwill_dec_ptr_OrderBook_d9452d61(dec *codegen.Decoder) *OrderBook {
	if !dec.Bool() {
		return nil
	}
	var res OrderBook
	(&res).WeaverUnmarshal(dec)
	return &res
}

func servicetwill_enc_ptr_ListFilters_b6166968(enc *codegen.Encoder, arg *ListFilters) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func servicetwill_dec_ptr_ListFilters_b6166968(dec *codegen.Decoder) *ListFilters {
	if !dec.Bool() {
		return nil
	}
	var res ListFilters
	(&res).WeaverUnmarshal(dec)
	return &res
}

func servicetwill_enc_slice_ptr_Market_0ccb1e02(enc *codegen.Encoder, arg []*types.Market) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for i := 0; i < len(arg); i++ {
		servicetwill_enc_ptr_Market_c7aa54b9(enc, arg[i])
	}
}

func servicetwill_dec_slice_ptr_Market_0ccb1e02(dec *codegen.Decoder) []*types.Market {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make([]*types.Market, n)
	for i := 0; i < n; i++ {
		res[i] = servicetwill_dec_ptr_Market_c7aa54b9(dec)
	}
	return res
}

// Size implementations.

// servicetwill_size_ptr_ListFilters_b6166968 returns the size (in bytes) of the serialization
// of the provided type.
func servicetwill_size_ptr_ListFilters_b6166968(x *ListFilters) int {
	if x == nil {
		return 1
	} else {
		return 1 + servicetwill_size_ListFilters_f7a95a88(&*x)
	}
}

// servicetwill_size_ListFilters_f7a95a88 returns the size (in bytes) of the serialization
// of the provided type.
func servicetwill_size_ListFilters_f7a95a88(x *ListFilters) int {
	size := 0
	size += 0
	size += (4 + len(x.MerchantID))
	size += (4 + len(x.EventID))
	size += (4 + len(x.Status))
	size += 8
	size += 8
	return size
}
