// Code generated by "twill generate". DO NOT EDIT.
//go:build !ignoreTwillGen

package event

import (
	"context"
	"errors"
	"fmt"
	"github.com/afun-game/predictmarket-saas/pkg/types"
	"github.com/nxsky/twill"
	"github.com/nxsky/twill/runtime/codegen"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "github.com/afun-game/predictmarket-saas/internal/event/Service",
		Iface: reflect.TypeOf((*Service)(nil)).Elem(),
		Impl:  reflect.TypeOf(implementation{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return service_local_stub{impl: impl.(Service), tracer: tracer, createMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/event/Service", Method: "Create", Remote: false, Generated: true}), getMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/event/Service", Method: "Get", Remote: false, Generated: true}), listMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/event/Service", Method: "List", Remote: false, Generated: true}), resolveMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/event/Service", Method: "Resolve", Remote: false, Generated: true}), resolveSourceMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/event/Service", Method: "ResolveSource", Remote: false, Generated: true}), syncSourceMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/event/Service", Method: "SyncSource", Remote: false, Generated: true}), updateMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/event/Service", Method: "Update", Remote: false, Generated: true}), updateStatusMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/event/Service", Method: "UpdateStatus", Remote: false, Generated: true})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return service_client_stub{stub: stub, createMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/event/Service", Method: "Create", Remote: true, Generated: true}), getMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/event/Service", Method: "Get", Remote: true, Generated: true}), listMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/event/Service", Method: "List", Remote: true, Generated: true}), resolveMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/event/Service", Method: "Resolve", Remote: true, Generated: true}), resolveSourceMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/event/Service", Method: "ResolveSource", Remote: true, Generated: true}), syncSourceMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/event/Service", Method: "SyncSource", Remote: true, Generated: true}), updateMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/event/Service", Method: "Update", Remote: true, Generated: true}), updateStatusMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/event/Service", Method: "UpdateStatus", Remote: true, Generated: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return service_server_stub{impl: impl.(Service), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return service_reflect_stub{caller: caller}
		},
		RefData: "",
	})
}

// twill.InstanceOf checks.
var _ twill.InstanceOf[Service] = (*implementation)(nil)

// twill.Router checks.
var _ twill.Unrouted = (*implementation)(nil)

// Local stub implementations.

type service_local_stub struct {
	impl                 Service
	tracer               trace.Tracer
	createMetrics        *codegen.MethodMetrics
	getMetrics           *codegen.MethodMetrics
	listMetrics          *codegen.MethodMetrics
	resolveMetrics       *codegen.MethodMetrics
	resolveSourceMetrics *codegen.MethodMetrics
	syncSourceMetrics    *codegen.MethodMetrics
	updateMetrics        *codegen.MethodMetrics
	updateStatusMetrics  *codegen.MethodMetrics
}

// Check that service_local_stub implements the Service interface.
var _ Service = (*service_local_stub)(nil)

func (s service_local_stub) Create(ctx context.Context, a0 *CreateRequest) (r0 *types.Event, err error) {
	// Update metrics.
	begin := s.createMetrics.Begin()
	defer func() { s.createMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "event.Service.Create", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Create(ctx, a0)
}

func (s service_local_stub) Get(ctx context.Context, a0 string) (r0 *types.Event, err error) {
	// Update metrics.
	begin := s.getMetrics.Begin()
	defer func() { s.getMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "event.Service.Get", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Get(ctx, a0)
}

func (s service_local_stub) List(ctx context.Context, a0 *ListFilters) (r0 []*types.Event, r1 int, err error) {
	// Update metrics.
	begin := s.listMetrics.Begin()
	defer func() { s.listMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "event.Service.List", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.List(ctx, a0)
}

func (s service_local_stub) Resolve(ctx context.Context, a0 string, a1 string) (err error) {
	// Update metrics.
	begin := s.resolveMetrics.Begin()
	defer func() { s.resolveMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "event.Service.Resolve", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Resolve(ctx, a0, a1)
}

func (s service_local_stub) ResolveSource(ctx context.Context, a0 string, a1 string) (err error) {
	// Update metrics.
	begin := s.resolveSourceMetrics.Begin()
	defer func() { s.resolveSourceMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "event.Service.ResolveSource", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.ResolveSource(ctx, a0, a1)
}

func (s service_local_stub) SyncSource(ctx context.Context, a0 *SyncRequest) (err error) {
	// Update metrics.
	begin := s.syncSourceMetrics.Begin()
	defer func() { s.syncSourceMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "event.Service.SyncSource", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.SyncSource(ctx, a0)
}

func (s service_local_stub) Update(ctx context.Context, a0 string, a1 *UpdateRequest) (r0 *types.Event, err error) {
	// Update metrics.
	begin := s.updateMetrics.Begin()
	defer func() { s.updateMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "event.Service.Update", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Update(ctx, a0, a1)
}

func (s service_local_stub) UpdateStatus(ctx context.Context, a0 string, a1 string) (err error) {
	// Update metrics.
	begin := s.updateStatusMetrics.Begin()
	defer func() { s.updateStatusMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "event.Service.UpdateStatus", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.UpdateStatus(ctx, a0, a1)
}

// Client stub implementations.

type service_client_stub struct {
	stub                 codegen.Stub
	createMetrics        *codegen.MethodMetrics
	getMetrics           *codegen.MethodMetrics
	listMetrics          *codegen.MethodMetrics
	resolveMetrics       *codegen.MethodMetrics
	resolveSourceMetrics *codegen.MethodMetrics
	syncSourceMetrics    *codegen.MethodMetrics
	updateMetrics        *codegen.MethodMetrics
	updateStatusMetrics  *codegen.MethodMetrics
}

// Check that service_client_stub implements the Service interface.
var _ Service = (*service_client_stub)(nil)

func (s service_client_stub) Create(ctx context.Context, a0 *CreateRequest) (r0 *types.Event, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.createMetrics.Begin()
	defer func() { s.createMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "event.Service.Create", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += servicetwill_size_ptr_CreateRequest_05de99cc(a0)
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	servicetwill_enc_ptr_CreateRequest_05de99cc(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = servicetwill_dec_ptr_Event_e8a4a956(dec)
	err = dec.Error()
	return
}

func (s service_client_stub) Get(ctx context.Context, a0 string) (r0 *types.Event, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getMetrics.Begin()
	defer func() { s.getMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "event.Service.Get", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 1, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = servicetwill_dec_ptr_Event_e8a4a956(dec)
	err = dec.Error()
	return
}

func (s service_client_stub) List(ctx context.Context, a0 *ListFilters) (r0 []*types.Event, r1 int, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.listMetrics.Begin()
	defer func() { s.listMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "event.Service.List", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += servicetwill_size_ptr_ListFilters_937825f4(a0)
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	servicetwill_enc_ptr_ListFilters_937825f4(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 2, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = servicetwill_dec_slice_ptr_Event_1e2c8ce4(dec)
	r1 = dec.Int()
	err = dec.Error()
	return
}

func (s service_client_stub) Resolve(ctx context.Context, a0 string, a1 string) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.resolveMetrics.Begin()
	defer func() { s.resolveMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "event.Service.Resolve", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += (4 + len(a1))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	enc.String(a1)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 3, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

func (s service_client_stub) ResolveSource(ctx context.Context, a0 string, a1 string) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.resolveSourceMetrics.Begin()
	defer func() { s.resolveSourceMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "event.Service.ResolveSource", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += (4 + len(a1))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	enc.String(a1)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 4, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

func (s service_client_stub) SyncSource(ctx context.Context, a0 *SyncRequest) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.syncSourceMetrics.Begin()
	defer func() { s.syncSourceMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "event.Service.SyncSource", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += servicetwill_size_ptr_SyncRequest_d6a6bd1d(a0)
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	servicetwill_enc_ptr_SyncRequest_d6a6bd1d(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 5, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

func (s service_client_stub) Update(ctx context.Context, a0 string, a1 *UpdateRequest) (r0 *types.Event, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.updateMetrics.Begin()
	defer func() { s.updateMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "event.Service.Update", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += servicetwill_size_ptr_UpdateRequest_70ee0773(a1)
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	servicetwill_enc_ptr_UpdateRequest_70ee0773(enc, a1)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 6, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = servicetwill_dec_ptr_Event_e8a4a956(dec)
	err = dec.Error()
	return
}

func (s service_client_stub) UpdateStatus(ctx context.Context, a0 string, a1 string) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.updateStatusMetrics.Begin()
	defer func() { s.updateStatusMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "event.Service.UpdateStatus", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += (4 + len(a1))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	enc.String(a1)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 7, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

// Note that "twill generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][24]struct{}](`

ERROR: You generated this file with 'twill generate' v0.24.7 (codegen
version v0.24.0). The generated code is incompatible with the version of the
github.com/nxsky/twill module that you're using. The twill module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/nxsky/twill

We recommend updating the twill module and the 'twill generate' command by
running the following.

    go get github.com/nxsky/twill@latest
    go install github.com/nxsky/twill/cmd/twill@latest

Then, re-run 'twill generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/Twill/twill/issues.

`)

// Server stub implementations.

type service_server_stub struct {
	impl    Service
	addLoad func(key uint64, load float64)
}

// Check that service_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*service_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s service_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "Create":
		return s.create
	case "Get":
		return s.get
	case "List":
		return s.list
	case "Resolve":
		return s.resolve
	case "ResolveSource":
		return s.resolveSource
	case "SyncSource":
		return s.syncSource
	case "Update":
		return s.update
	case "UpdateStatus":
		return s.updateStatus
	default:
		return nil
	}
}

func (s service_server_stub) create(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *CreateRequest
	a0 = servicetwill_dec_ptr_CreateRequest_05de99cc(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.Create(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	servicetwill_enc_ptr_Event_e8a4a956(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) get(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.Get(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	servicetwill_enc_ptr_Event_e8a4a956(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) list(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *ListFilters
	a0 = servicetwill_dec_ptr_ListFilters_937825f4(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, r1, appErr := s.impl.List(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	servicetwill_enc_slice_ptr_Event_1e2c8ce4(enc, r0)
	enc.Int(r1)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) resolve(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 string
	a1 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.Resolve(ctx, a0, a1)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) resolveSource(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 string
	a1 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.ResolveSource(ctx, a0, a1)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) syncSource(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *SyncRequest
	a0 = servicetwill_dec_ptr_SyncRequest_d6a6bd1d(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.SyncSource(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) update(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 *UpdateRequest
	a1 = servicetwill_dec_ptr_UpdateRequest_70ee0773(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.Update(ctx, a0, a1)

	// Encode the results.
	enc := codegen.NewEncoder()
	servicetwill_enc_ptr_Event_e8a4a956(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) updateStatus(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 string
	a1 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.UpdateStatus(ctx, a0, a1)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

// Reflect stub implementations.

type service_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that service_reflect_stub implements the Service interface.
var _ Service = (*service_reflect_stub)(nil)

func (s service_reflect_stub) Create(ctx context.Context, a0 *CreateRequest) (r0 *types.Event, err error) {
	err = s.caller("Create", ctx, []any{a0}, []any{&r0})
	return
}

func (s service_reflect_stub) Get(ctx context.Context, a0 string) (r0 *types.Event, err error) {
	err = s.caller("Get", ctx, []any{a0}, []any{&r0})
	return
}

func (s service_reflect_stub) List(ctx context.Context, a0 *ListFilters) (r0 []*types.Event, r1 int, err error) {
	err = s.caller("List", ctx, []any{a0}, []any{&r0, &r1})
	return
}

func (s service_reflect_stub) Resolve(ctx context.Context, a0 string, a1 string) (err error) {
	err = s.caller("Resolve", ctx, []any{a0, a1}, []any{})
	return
}

func (s service_reflect_stub) ResolveSource(ctx context.Context, a0 string, a1 string) (err error) {
	err = s.caller("ResolveSource", ctx, []any{a0, a1}, []any{})
	return
}

func (s service_reflect_stub) SyncSource(ctx context.Context, a0 *SyncRequest) (err error) {
	err = s.caller("SyncSource", ctx, []any{a0}, []any{})
	return
}

func (s service_reflect_stub) Update(ctx context.Context, a0 string, a1 *UpdateRequest) (r0 *types.Event, err error) {
	err = s.caller("Update", ctx, []any{a0, a1}, []any{&r0})
	return
}

func (s service_reflect_stub) UpdateStatus(ctx context.Context, a0 string, a1 string) (err error) {
	err = s.caller("UpdateStatus", ctx, []any{a0, a1}, []any{})
	return
}

// AutoMarshal implementations.

var _ codegen.AutoMarshal = (*CreateRequest)(nil)

type __is_CreateRequest[T ~struct {
	twill.AutoMarshal
	SourceType     string "json:\"source_type\""
	SourceID       string "json:\"source_id\""
	Title          string "json:\"title\""
	Description    string "json:\"description\""
	Category       string "json:\"category\""
	EndTime        string "json:\"end_time\""
	ResolutionTime string "json:\"resolution_time\""
}] struct{}

var _ __is_CreateRequest[CreateRequest]

func (x *CreateRequest) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("CreateRequest.WeaverMarshal: nil receiver"))
	}
	enc.String(x.SourceType)
	enc.String(x.SourceID)
	enc.String(x.Title)
	enc.String(x.Description)
	enc.String(x.Category)
	enc.String(x.EndTime)
	enc.String(x.ResolutionTime)
}

func (x *CreateRequest) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("CreateRequest.WeaverUnmarshal: nil receiver"))
	}
	x.SourceType = dec.String()
	x.SourceID = dec.String()
	x.Title = dec.String()
	x.Description = dec.String()
	x.Category = dec.String()
	x.EndTime = dec.String()
	x.ResolutionTime = dec.String()
}

var _ codegen.AutoMarshal = (*ListFilters)(nil)

type __is_ListFilters[T ~struct {
	twill.AutoMarshal
	Category string "json:\"category,omitempty\""
	Status   string "json:\"status,omitempty\""
	Page     int    "json:\"page,omitempty\""
	Limit    int    "json:\"limit,omitempty\""
}] struct{}

var _ __is_ListFilters[ListFilters]

func (x *ListFilters) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("ListFilters.WeaverMarshal: nil receiver"))
	}
	enc.String(x.Category)
	enc.String(x.Status)
	enc.Int(x.Page)
	enc.Int(x.Limit)
}

func (x *ListFilters) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("ListFilters.WeaverUnmarshal: nil receiver"))
	}
	x.Category = dec.String()
	x.Status = dec.String()
	x.Page = dec.Int()
	x.Limit = dec.Int()
}

var _ codegen.AutoMarshal = (*SyncRequest)(nil)

type __is_SyncRequest[T ~struct {
	twill.AutoMarshal
	SourceID       string "json:\"source_id\""
	Title          string "json:\"title\""
	Description    string "json:\"description\""
	Category       string "json:\"category\""
	EndTime        string "json:\"end_time\""
	ResolutionTime string "json:\"resolution_time\""
	Status         string "json:\"status\""
}] struct{}

var _ __is_SyncRequest[SyncRequest]

func (x *SyncRequest) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("SyncRequest.WeaverMarshal: nil receiver"))
	}
	enc.String(x.SourceID)
	enc.String(x.Title)
	enc.String(x.Description)
	enc.String(x.Category)
	enc.String(x.EndTime)
	enc.String(x.ResolutionTime)
	enc.String(x.Status)
}

func (x *SyncRequest) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("SyncRequest.WeaverUnmarshal: nil receiver"))
	}
	x.SourceID = dec.String()
	x.Title = dec.String()
	x.Description = dec.String()
	x.Category = dec.String()
	x.EndTime = dec.String()
	x.ResolutionTime = dec.String()
	x.Status = dec.String()
}

var _ codegen.AutoMarshal = (*UpdateRequest)(nil)

type __is_UpdateRequest[T ~struct {
	twill.AutoMarshal
	Title          *string "json:\"title,omitempty\""
	Description    *string "json:\"description,omitempty\""
	ResolutionTime *string "json:\"resolution_time,omitempty\""
}] struct{}

var _ __is_UpdateRequest[UpdateRequest]

func (x *UpdateRequest) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("UpdateRequest.WeaverMarshal: nil receiver"))
	}
	servicetwill_enc_ptr_string_3e89801b(enc, x.Title)
	servicetwill_enc_ptr_string_3e89801b(enc, x.Description)
	servicetwill_enc_ptr_string_3e89801b(enc, x.ResolutionTime)
}

func (x *UpdateRequest) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("UpdateRequest.WeaverUnmarshal: nil receiver"))
	}
	x.Title = servicetwill_dec_ptr_string_3e89801b(dec)
	x.Description = servicetwill_dec_ptr_string_3e89801b(dec)
	x.ResolutionTime = servicetwill_dec_ptr_string_3e89801b(dec)
}

func servicetwill_enc_ptr_string_3e89801b(enc *codegen.Encoder, arg *string) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.String(*arg)
	}
}

func servicetwill_dec_ptr_string_3e89801b(dec *codegen.Decoder) *string {
	if !dec.Bool() {
		return nil
	}
	var res string
	res = dec.String()
	return &res
}

// Encoding/decoding implementations.

func servicetwill_enc_ptr_CreateRequest_05de99cc(enc *codegen.Encoder, arg *CreateRequest) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func servicetwill_dec_ptr_CreateRequest_05de99cc(dec *codegen.Decoder) *CreateRequest {
	if !dec.Bool() {
		return nil
	}
	var res CreateRequest
	(&res).WeaverUnmarshal(dec)
	return &res
}

func servicetwill_enc_ptr_Event_e8a4a956(enc *codegen.Encoder, arg *types.Event) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func servicetwill_dec_ptr_Event_e8a4a956(dec *codegen.Decoder) *types.Event {
	if !dec.Bool() {
		return nil
	}
	var res types.Event
	(&res).WeaverUnmarshal(dec)
	return &res
}

func servicetwill_enc_ptr_ListFilters_937825f4(enc *codegen.Encoder, arg *ListFilters) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func servicetwill_dec_ptr_ListFilters_937825f4(dec *codegen.Decoder) *ListFilters {
	if !dec.Bool() {
		return nil
	}
	var res ListFilters
	(&res).WeaverUnmarshal(dec)
	return &res
}

func servicetwill_enc_slice_ptr_Event_1e2c8ce4(enc *codegen.Encoder, arg []*types.Event) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for i := 0; i < len(arg); i++ {
		servicetwill_enc_ptr_Event_e8a4a956(enc, arg[i])
	}
}

func servicetwill_dec_slice_ptr_Event_1e2c8ce4(dec *codegen.Decoder) []*types.Event {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make([]*types.Event, n)
	for i := 0; i < n; i++ {
		res[i] = servicetwill_dec_ptr_Event_e8a4a956(dec)
	}
	return res
}

func servicetwill_enc_ptr_SyncRequest_d6a6bd1d(enc *codegen.Encoder, arg *SyncRequest) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func servicetwill_dec_ptr_SyncRequest_d6a6bd1d(dec *codegen.Decoder) *SyncRequest {
	if !dec.Bool() {
		return nil
	}
	var res SyncRequest
	(&res).WeaverUnmarshal(dec)
	return &res
}

func servicetwill_enc_ptr_UpdateRequest_70ee0773(enc *codegen.Encoder, arg *UpdateRequest) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func servicetwill_dec_ptr_UpdateRequest_70ee0773(dec *codegen.Decoder) *UpdateRequest {
	if !dec.Bool() {
		return nil
	}
	var res UpdateRequest
	(&res).WeaverUnmarshal(dec)
	return &res
}

// Size implementations.

// servicetwill_size_ptr_CreateRequest_05de99cc returns the size (in bytes) of the serialization
// of the provided type.
func servicetwill_size_ptr_CreateRequest_05de99cc(x *CreateRequest) int {
	if x == nil {
		return 1
	} else {
		return 1 + servicetwill_size_CreateRequest_23f6efda(&*x)
	}
}

// servicetwill_size_ptr_ListFilters_937825f4 returns the size (in bytes) of the serialization
// of the provided type.
func servicetwill_size_ptr_ListFilters_937825f4(x *ListFilters) int {
	if x == nil {
		return 1
	} else {
		return 1 + servicetwill_size_ListFilters_89f1ae8b(&*x)
	}
}

// servicetwill_size_ptr_SyncRequest_d6a6bd1d returns the size (in bytes) of the serialization
// of the provided type.
func servicetwill_size_ptr_SyncRequest_d6a6bd1d(x *SyncRequest) int {
	if x == nil {
		return 1
	} else {
		return 1 + servicetwill_size_SyncRequest_61147890(&*x)
	}
}

// servicetwill_size_ptr_UpdateRequest_70ee0773 returns the size (in bytes) of the serialization
// of the provided type.
func servicetwill_size_ptr_UpdateRequest_70ee0773(x *UpdateRequest) int {
	if x == nil {
		return 1
	} else {
		return 1 + servicetwill_size_UpdateRequest_d38b9db0(&*x)
	}
}

// servicetwill_size_ptr_string_3e89801b returns the size (in bytes) of the serialization
// of the provided type.
func servicetwill_size_ptr_string_3e89801b(x *string) int {
	if x == nil {
		return 1
	} else {
		return 1 + (4 + len(*x))
	}
}

// servicetwill_size_CreateRequest_23f6efda returns the size (in bytes) of the serialization
// of the provided type.
func servicetwill_size_CreateRequest_23f6efda(x *CreateRequest) int {
	size := 0
	size += 0
	size += (4 + len(x.SourceType))
	size += (4 + len(x.SourceID))
	size += (4 + len(x.Title))
	size += (4 + len(x.Description))
	size += (4 + len(x.Category))
	size += (4 + len(x.EndTime))
	size += (4 + len(x.ResolutionTime))
	return size
}

// servicetwill_size_ListFilters_89f1ae8b returns the size (in bytes) of the serialization
// of the provided type.
func servicetwill_size_ListFilters_89f1ae8b(x *ListFilters) int {
	size := 0
	size += 0
	size += (4 + len(x.Category))
	size += (4 + len(x.Status))
	size += 8
	size += 8
	return size
}

// servicetwill_size_SyncRequest_61147890 returns the size (in bytes) of the serialization
// of the provided type.
func servicetwill_size_SyncRequest_61147890(x *SyncRequest) int {
	size := 0
	size += 0
	size += (4 + len(x.SourceID))
	size += (4 + len(x.Title))
	size += (4 + len(x.Description))
	size += (4 + len(x.Category))
	size += (4 + len(x.EndTime))
	size += (4 + len(x.ResolutionTime))
	size += (4 + len(x.Status))
	return size
}

// servicetwill_size_UpdateRequest_d38b9db0 returns the size (in bytes) of the serialization
// of the provided type.
func servicetwill_size_UpdateRequest_d38b9db0(x *UpdateRequest) int {
	size := 0
	size += 0
	size += servicetwill_size_ptr_string_3e89801b(x.Title)
	size += servicetwill_size_ptr_string_3e89801b(x.Description)
	size += servicetwill_size_ptr_string_3e89801b(x.ResolutionTime)
	return size
}
