// Code generated by "twill generate". DO NOT EDIT.
//go:build !ignoreTwillGen

package order

import (
	"context"
	"errors"
	"fmt"
	"github.com/afun-game/predictmarket-saas/internal/market"
	"github.com/afun-game/predictmarket-saas/pkg/types"
	"github.com/nxsky/twill"
	"github.com/nxsky/twill/runtime/codegen"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "github.com/afun-game/predictmarket-saas/internal/order/Service",
		Iface: reflect.TypeOf((*Service)(nil)).Elem(),
		Impl:  reflect.TypeOf(implementation{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return service_local_stub{impl: impl.(Service), tracer: tracer, cancelMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/order/Service", Method: "Cancel", Remote: false, Generated: true}), createMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/order/Service", Method: "Create", Remote: false, Generated: true}), getMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/order/Service", Method: "Get", Remote: false, Generated: true}), getOrderBookMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/order/Service", Method: "GetOrderBook", Remote: false, Generated: true}), listMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/order/Service", Method: "List", Remote: false, Generated: true}), listByMarketMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/order/Service", Method: "ListByMarket", Remote: false, Generated: true}), listByUserMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/order/Service", Method: "ListByUser", Remote: false, Generated: true}), listCursorMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/order/Service", Method: "ListCursor", Remote: false, Generated: true})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return service_client_stub{stub: stub, cancelMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/order/Service", Method: "Cancel", Remote: true, Generated: true}), createMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/order/Service", Method: "Create", Remote: true, Generated: true}), getMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/order/Service", Method: "Get", Remote: true, Generated: true}), getOrderBookMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/order/Service", Method: "GetOrderBook", Remote: true, Generated: true}), listMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/order/Service", Method: "List", Remote: true, Generated: true}), listByMarketMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/order/Service", Method: "ListByMarket", Remote: true, Generated: true}), listByUserMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/order/Service", Method: "ListByUser", Remote: true, Generated: true}), listCursorMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/order/Service", Method: "ListCursor", Remote: true, Generated: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return service_server_stub{impl: impl.(Service), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return service_reflect_stub{caller: caller}
		},
		RefData: "⟦bd0f6d2a:wEaVeReDgE:github.com/afun-game/predictmarket-saas/internal/order/Service→github.com/afun-game/predictmarket-saas/internal/market/Service⟧\n⟦b170301a:wEaVeReDgE:github.com/afun-game/predictmarket-saas/internal/order/Service→github.com/afun-game/predictmarket-saas/internal/wallet/Service⟧\n",
	})
}

// twill.InstanceOf checks.
var _ twill.InstanceOf[Service] = (*implementation)(nil)

// twill.Router checks.
var _ twill.Unrouted = (*implementation)(nil)

// Local stub implementations.

type service_local_stub struct {
	impl                Service
	tracer              trace.Tracer
	cancelMetrics       *codegen.MethodMetrics
	createMetrics       *codegen.MethodMetrics
	getMetrics          *codegen.MethodMetrics
	getOrderBookMetrics *codegen.MethodMetrics
	listMetrics         *codegen.MethodMetrics
	listByMarketMetrics *codegen.MethodMetrics
	listByUserMetrics   *codegen.MethodMetrics
	listCursorMetrics   *codegen.MethodMetrics
}

// Check that service_local_stub implements the Service interface.
var _ Service = (*service_local_stub)(nil)

func (s service_local_stub) Cancel(ctx context.Context, a0 string) (err error) {
	// Update metrics.
	begin := s.cancelMetrics.Begin()
	defer func() { s.cancelMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "order.Service.Cancel", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Cancel(ctx, a0)
}

func (s service_local_stub) Create(ctx context.Context, a0 *CreateRequest) (r0 *types.Order, err error) {
	// Update metrics.
	begin := s.createMetrics.Begin()
	defer func() { s.createMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "order.Service.Create", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Create(ctx, a0)
}

func (s service_local_stub) Get(ctx context.Context, a0 string) (r0 *types.Order, err error) {
	// Update metrics.
	begin := s.getMetrics.Begin()
	defer func() { s.getMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "order.Service.Get", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Get(ctx, a0)
}

func (s service_local_stub) GetOrderBook(ctx context.Context, a0 string) (r0 *market.OrderBook, err error) {
	// Update metrics.
	begin := s.getOrderBookMetrics.Begin()
	defer func() { s.getOrderBookMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "order.Service.GetOrderBook", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetOrderBook(ctx, a0)
}

func (s service_local_stub) List(ctx context.Context, a0 *ListFilters) (r0 []*types.Order, r1 int, err error) {
	// Update metrics.
	begin := s.listMetrics.Begin()
	defer func() { s.listMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "order.Service.List", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.List(ctx, a0)
}

func (s service_local_stub) ListByMarket(ctx context.Context, a0 string, a1 int, a2 int) (r0 []*types.Order, r1 int, err error) {
	// Update metrics.
	begin := s.listByMarketMetrics.Begin()
	defer func() { s.listByMarketMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "order.Service.ListByMarket", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.ListByMarket(ctx, a0, a1, a2)
}

func (s service_local_stub) ListByUser(ctx context.Context, a0 string, a1 string, a2 int, a3 int) (r0 []*types.Order, r1 int, err error) {
	// Update metrics.
	begin := s.listByUserMetrics.Begin()
	defer func() { s.listByUserMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "order.Service.ListByUser", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.ListByUser(ctx, a0, a1, a2, a3)
}

func (s service_local_stub) ListCursor(ctx context.Context, a0 *ListFilters) (r0 *CursorPage, err error) {
	// Update metrics.
	begin := s.listCursorMetrics.Begin()
	defer func() { s.listCursorMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "order.Service.ListCursor", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.ListCursor(ctx, a0)
}

// Client stub implementations.

type service_client_stub struct {
	stub                codegen.Stub
	cancelMetrics       *codegen.MethodMetrics
	createMetrics       *codegen.MethodMetrics
	getMetrics          *codegen.MethodMetrics
	getOrderBookMetrics *codegen.MethodMetrics
	listMetrics         *codegen.MethodMetrics
	listByMarketMetrics *codegen.MethodMetrics
	listByUserMetrics   *codegen.MethodMetrics
	listCursorMetrics   *codegen.MethodMetrics
}

// Check that service_client_stub implements the Service interface.
var _ Service = (*service_client_stub)(nil)

func (s service_client_stub) Cancel(ctx context.Context, a0 string) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.cancelMetrics.Begin()
	defer func() { s.cancelMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "order.Service.Cancel", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

func (s service_client_stub) Create(ctx context.Context, a0 *CreateRequest) (r0 *types.Order, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.createMetrics.Begin()
	defer func() { s.createMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "order.Service.Create", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += servicetwill_size_ptr_CreateRequest_a61386f0(a0)
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	servicetwill_enc_ptr_CreateRequest_a61386f0(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 1, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = servicetwill_dec_ptr_Order_9a506ee4(dec)
	err = dec.Error()
	return
}

func (s service_client_stub) Get(ctx context.Context, a0 string) (r0 *types.Order, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getMetrics.Begin()
	defer func() { s.getMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "order.Service.Get", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 2, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = servicetwill_dec_ptr_Order_9a506ee4(dec)
	err = dec.Error()
	return
}

func (s service_client_stub) GetOrderBook(ctx context.Context, a0 string) (r0 *market.OrderBook, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getOrderBookMetrics.Begin()
	defer func() { s.getOrderBookMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "order.Service.GetOrderBook", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 3, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = servicetwill_dec_ptr_OrderBook_d9452d61(dec)
	err = dec.Error()
	return
}

func (s service_client_stub) List(ctx context.Context, a0 *ListFilters) (r0 []*types.Order, r1 int, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.listMetrics.Begin()
	defer func() { s.listMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "order.Service.List", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += servicetwill_size_ptr_ListFilters_aa4fcb30(a0)
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	servicetwill_enc_ptr_ListFilters_aa4fcb30(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 4, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = servicetwill_dec_slice_ptr_Order_c2d96aea(dec)
	r1 = dec.Int()
	err = dec.Error()
	return
}

func (s service_client_stub) ListByMarket(ctx context.Context, a0 string, a1 int, a2 int) (r0 []*types.Order, r1 int, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.listByMarketMetrics.Begin()
	defer func() { s.listByMarketMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "order.Service.ListByMarket", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += 8
	size += 8
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	enc.Int(a1)
	enc.Int(a2)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 5, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = servicetwill_dec_slice_ptr_Order_c2d96aea(dec)
	r1 = dec.Int()
	err = dec.Error()
	return
}

func (s service_client_stub) ListByUser(ctx context.Context, a0 string, a1 string, a2 int, a3 int) (r0 []*types.Order, r1 int, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.listByUserMetrics.Begin()
	defer func() { s.listByUserMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "order.Service.ListByUser", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += (4 + len(a1))
	size += 8
	size += 8
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	enc.String(a1)
	enc.Int(a2)
	enc.Int(a3)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 6, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = servicetwill_dec_slice_ptr_Order_c2d96aea(dec)
	r1 = dec.Int()
	err = dec.Error()
	return
}

func (s service_client_stub) ListCursor(ctx context.Context, a0 *ListFilters) (r0 *CursorPage, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.listCursorMetrics.Begin()
	defer func() { s.listCursorMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "order.Service.ListCursor", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += servicetwill_size_ptr_ListFilters_aa4fcb30(a0)
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	servicetwill_enc_ptr_ListFilters_aa4fcb30(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 7, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = servicetwill_dec_ptr_CursorPage_1a7d2ced(dec)
	err = dec.Error()
	return
}

// Note that "twill generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][24]struct{}](`

ERROR: You generated this file with 'twill generate' (devel) (codegen
version v0.24.0). The generated code is incompatible with the version of the
github.com/nxsky/twill module that you're using. The twill module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/nxsky/twill

We recommend updating the twill module and the 'twill generate' command by
running the following.

    go get github.com/nxsky/twill@latest
    go install github.com/nxsky/twill/cmd/twill@latest

Then, re-run 'twill generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/Twill/twill/issues.

`)

// Server stub implementations.

type service_server_stub struct {
	impl    Service
	addLoad func(key uint64, load float64)
}

// Check that service_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*service_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s service_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "Cancel":
		return s.cancel
	case "Create":
		return s.create
	case "Get":
		return s.get
	case "GetOrderBook":
		return s.getOrderBook
	case "List":
		return s.list
	case "ListByMarket":
		return s.listByMarket
	case "ListByUser":
		return s.listByUser
	case "ListCursor":
		return s.listCursor
	default:
		return nil
	}
}

func (s service_server_stub) cancel(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.Cancel(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) create(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *CreateRequest
	a0 = servicetwill_dec_ptr_CreateRequest_a61386f0(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.Create(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	servicetwill_enc_ptr_Order_9a506ee4(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) get(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.Get(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	servicetwill_enc_ptr_Order_9a506ee4(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) getOrderBook(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetOrderBook(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	servicetwill_enc_ptr_OrderBook_d9452d61(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) list(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *ListFilters
	a0 = servicetwill_dec_ptr_ListFilters_aa4fcb30(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, r1, appErr := s.impl.List(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	servicetwill_enc_slice_ptr_Order_c2d96aea(enc, r0)
	enc.Int(r1)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) listByMarket(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 int
	a1 = dec.Int()
	var a2 int
	a2 = dec.Int()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, r1, appErr := s.impl.ListByMarket(ctx, a0, a1, a2)

	// Encode the results.
	enc := codegen.NewEncoder()
	servicetwill_enc_slice_ptr_Order_c2d96aea(enc, r0)
	enc.Int(r1)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) listByUser(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 string
	a1 = dec.String()
	var a2 int
	a2 = dec.Int()
	var a3 int
	a3 = dec.Int()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, r1, appErr := s.impl.ListByUser(ctx, a0, a1, a2, a3)

	// Encode the results.
	enc := codegen.NewEncoder()
	servicetwill_enc_slice_ptr_Order_c2d96aea(enc, r0)
	enc.Int(r1)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) listCursor(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *ListFilters
	a0 = servicetwill_dec_ptr_ListFilters_aa4fcb30(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.ListCursor(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	servicetwill_enc_ptr_CursorPage_1a7d2ced(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

// Reflect stub implementations.

type service_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that service_reflect_stub implements the Service interface.
var _ Service = (*service_reflect_stub)(nil)

func (s service_reflect_stub) Cancel(ctx context.Context, a0 string) (err error) {
	err = s.caller("Cancel", ctx, []any{a0}, []any{})
	return
}

func (s service_reflect_stub) Create(ctx context.Context, a0 *CreateRequest) (r0 *types.Order, err error) {
	err = s.caller("Create", ctx, []any{a0}, []any{&r0})
	return
}

func (s service_reflect_stub) Get(ctx context.Context, a0 string) (r0 *types.Order, err error) {
	err = s.caller("Get", ctx, []any{a0}, []any{&r0})
	return
}

func (s service_reflect_stub) GetOrderBook(ctx context.Context, a0 string) (r0 *market.OrderBook, err error) {
	err = s.caller("GetOrderBook", ctx, []any{a0}, []any{&r0})
	return
}

func (s service_reflect_stub) List(ctx context.Context, a0 *ListFilters) (r0 []*types.Order, r1 int, err error) {
	err = s.caller("List", ctx, []any{a0}, []any{&r0, &r1})
	return
}

func (s service_reflect_stub) ListByMarket(ctx context.Context, a0 string, a1 int, a2 int) (r0 []*types.Order, r1 int, err error) {
	err = s.caller("ListByMarket", ctx, []any{a0, a1, a2}, []any{&r0, &r1})
	return
}

func (s service_reflect_stub) ListByUser(ctx context.Context, a0 string, a1 string, a2 int, a3 int) (r0 []*types.Order, r1 int, err error) {
	err = s.caller("ListByUser", ctx, []any{a0, a1, a2, a3}, []any{&r0, &r1})
	return
}

func (s service_reflect_stub) ListCursor(ctx context.Context, a0 *ListFilters) (r0 *CursorPage, err error) {
	err = s.caller("ListCursor", ctx, []any{a0}, []any{&r0})
	return
}

// AutoMarshal implementations.

var _ codegen.AutoMarshal = (*CreateRequest)(nil)

type __is_CreateRequest[T ~struct {
	twill.AutoMarshal
	MerchantID     string  "json:\"merchant_id\""
	UserID         string  "json:\"user_id\""
	MarketID       string  "json:\"market_id\""
	Type           string  "json:\"type\""
	Option         string  "json:\"option\""
	Amount         float64 "json:\"amount\""
	Currency       string  "json:\"currency\""
	Price          float64 "json:\"price\""
	TimeInForce    string  "json:\"time_in_force,omitempty\""
	IdempotencyKey string  "json:\"-\""
}] struct{}

var _ __is_CreateRequest[CreateRequest]

func (x *CreateRequest) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("CreateRequest.WeaverMarshal: nil receiver"))
	}
	enc.String(x.MerchantID)
	enc.String(x.UserID)
	enc.String(x.MarketID)
	enc.String(x.Type)
	enc.String(x.Option)
	enc.Float64(x.Amount)
	enc.String(x.Currency)
	enc.Float64(x.Price)
	enc.String(x.TimeInForce)
	enc.String(x.IdempotencyKey)
}

func (x *CreateRequest) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("CreateRequest.WeaverUnmarshal: nil receiver"))
	}
	x.MerchantID = dec.String()
	x.UserID = dec.String()
	x.MarketID = dec.String()
	x.Type = dec.String()
	x.Option = dec.String()
	x.Amount = dec.Float64()
	x.Currency = dec.String()
	x.Price = dec.Float64()
	x.TimeInForce = dec.String()
	x.IdempotencyKey = dec.String()
}

var _ codegen.AutoMarshal = (*CursorPage)(nil)

type __is_CursorPage[T ~struct {
	twill.AutoMarshal
	Orders     []*types.Order "json:\"orders\""
	NextCursor string         "json:\"next_cursor,omitempty\""
}] struct{}

var _ __is_CursorPage[CursorPage]

func (x *CursorPage) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("CursorPage.WeaverMarshal: nil receiver"))
	}
	servicetwill_enc_slice_ptr_Order_c2d96aea(enc, x.Orders)
	enc.String(x.NextCursor)
}

func (x *CursorPage) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("CursorPage.WeaverUnmarshal: nil receiver"))
	}
	x.Orders = servicetwill_dec_slice_ptr_Order_c2d96aea(dec)
	x.NextCursor = dec.String()
}

func servicetwill_enc_ptr_Order_9a506ee4(enc *codegen.Encoder, arg *types.Order) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func servicetwill_dec_ptr_Order_9a506ee4(dec *codegen.Decoder) *types.Order {
	if !dec.Bool() {
		return nil
	}
	var res types.Order
	(&res).WeaverUnmarshal(dec)
	return &res
}

func servicetwill_enc_slice_ptr_Order_c2d96aea(enc *codegen.Encoder, arg []*types.Order) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for i := 0; i < len(arg); i++ {
		servicetwill_enc_ptr_Order_9a506ee4(enc, arg[i])
	}
}

func servicetwill_dec_slice_ptr_Order_c2d96aea(dec *codegen.Decoder) []*types.Order {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make([]*types.Order, n)
	for i := 0; i < n; i++ {
		res[i] = servicetwill_dec_ptr_Order_9a506ee4(dec)
	}
	return res
}

var _ codegen.AutoMarshal = (*ListFilters)(nil)

type __is_ListFilters[T ~struct {
	twill.AutoMarshal
	MerchantID string "json:\"merchant_id,omitempty\""
	UserID     string "json:\"user_id,omitempty\""
	MarketID   string "json:\"market_id,omitempty\""
	Status     string "json:\"status,omitempty\""
	Cursor     string "json:\"cursor,omitempty\""
	Page       int    "json:\"page,omitempty\""
	Limit      int    "json:\"limit,omitempty\""
}] struct{}

var _ __is_ListFilters[ListFilters]

func (x *ListFilters) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("ListFilters.WeaverMarshal: nil receiver"))
	}
	enc.String(x.MerchantID)
	enc.String(x.UserID)
	enc.String(x.MarketID)
	enc.String(x.Status)
	enc.String(x.Cursor)
	enc.Int(x.Page)
	enc.Int(x.Limit)
}

func (x *ListFilters) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("ListFilters.WeaverUnmarshal: nil receiver"))
	}
	x.MerchantID = dec.String()
	x.UserID = dec.String()
	x.MarketID = dec.String()
	x.Status = dec.String()
	x.Cursor = dec.String()
	x.Page = dec.Int()
	x.Limit = dec.Int()
}

// Encoding/decoding implementations.

func servicetwill_enc_ptr_CreateRequest_a61386f0(enc *codegen.Encoder, arg *CreateRequest) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func servicetwill_dec_ptr_CreateRequest_a61386f0(dec *codegen.Decoder) *CreateRequest {
	if !dec.Bool() {
		return nil
	}
	var res CreateRequest
	(&res).WeaverUnmarshal(dec)
	return &res
}

func servicetwill_enc_ptr_OrderBook_d9452d61(enc *codegen.Encoder, arg *market.OrderBook) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func servicetwill_dec_ptr_OrderBook_d9452d61(dec *codegen.Decoder) *market.OrderBook {
	if !dec.Bool() {
		return nil
	}
	var res market.OrderBook
	(&res).WeaverUnmarshal(dec)
	return &res
}

func servicetwill_enc_ptr_ListFilters_aa4fcb30(enc *codegen.Encoder, arg *ListFilters) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func servicetwill_dec_ptr_ListFilters_aa4fcb30(dec *codegen.Decoder) *ListFilters {
	if !dec.Bool() {
		return nil
	}
	var res ListFilters
	(&res).WeaverUnmarshal(dec)
	return &res
}

func servicetwill_enc_ptr_CursorPage_1a7d2ced(enc *codegen.Encoder, arg *CursorPage) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func servicetwill_dec_ptr_CursorPage_1a7d2ced(dec *codegen.Decoder) *CursorPage {
	if !dec.Bool() {
		return nil
	}
	var res CursorPage
	(&res).WeaverUnmarshal(dec)
	return &res
}

// Size implementations.

// servicetwill_size_ptr_CreateRequest_a61386f0 returns the size (in bytes) of the serialization
// of the provided type.
func servicetwill_size_ptr_CreateRequest_a61386f0(x *CreateRequest) int {
	if x == nil {
		return 1
	} else {
		return 1 + servicetwill_size_CreateRequest_321011ed(&*x)
	}
}

// servicetwill_size_ptr_ListFilters_aa4fcb30 returns the size (in bytes) of the serialization
// of the provided type.
func servicetwill_size_ptr_ListFilters_aa4fcb30(x *ListFilters) int {
	if x == nil {
		return 1
	} else {
		return 1 + servicetwill_size_ListFilters_c6871b88(&*x)
	}
}

// servicetwill_size_CreateRequest_321011ed returns the size (in bytes) of the serialization
// of the provided type.
func servicetwill_size_CreateRequest_321011ed(x *CreateRequest) int {
	size := 0
	size += 0
	size += (4 + len(x.MerchantID))
	size += (4 + len(x.UserID))
	size += (4 + len(x.MarketID))
	size += (4 + len(x.Type))
	size += (4 + len(x.Option))
	size += 8
	size += (4 + len(x.Currency))
	size += 8
	size += (4 + len(x.TimeInForce))
	size += (4 + len(x.IdempotencyKey))
	return size
}

// servicetwill_size_ListFilters_c6871b88 returns the size (in bytes) of the serialization
// of the provided type.
func servicetwill_size_ListFilters_c6871b88(x *ListFilters) int {
	size := 0
	size += 0
	size += (4 + len(x.MerchantID))
	size += (4 + len(x.UserID))
	size += (4 + len(x.MarketID))
	size += (4 + len(x.Status))
	size += (4 + len(x.Cursor))
	size += 8
	size += 8
	return size
}
