// Code generated by "twill generate". DO NOT EDIT.
//go:build !ignoreTwillGen

package types

import (
	"fmt"
	"github.com/nxsky/twill"
	"github.com/nxsky/twill/runtime/codegen"
	"time"
)

// twill.InstanceOf checks.

// twill.Router checks.

// Local stub implementations.

// Client stub implementations.

// Note that "twill generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][24]struct{}](`

ERROR: You generated this file with 'twill generate' v0.24.7 (codegen
version v0.24.0). The generated code is incompatible with the version of the
github.com/nxsky/twill module that you're using. The twill module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/nxsky/twill

We recommend updating the twill module and the 'twill generate' command by
running the following.

    go get github.com/nxsky/twill@latest
    go install github.com/nxsky/twill/cmd/twill@latest

Then, re-run 'twill generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/Twill/twill/issues.

`)

// Server stub implementations.

// Reflect stub implementations.

// AutoMarshal implementations.

var _ codegen.AutoMarshal = (*Event)(nil)

type __is_Event[T ~struct {
	twill.AutoMarshal
	ID             string    "json:\"id\""
	SourceType     string    "json:\"source_type\""
	SourceID       string    "json:\"source_id\""
	Title          string    "json:\"title\""
	Description    string    "json:\"description\""
	Category       string    "json:\"category\""
	EndTime        time.Time "json:\"end_time\""
	ResolutionTime time.Time "json:\"resolution_time\""
	Status         string    "json:\"status\""
	Outcome        *string   "json:\"outcome,omitempty\""
	CreatedAt      time.Time "json:\"created_at\""
	UpdatedAt      time.Time "json:\"updated_at\""
}] struct{}

var _ __is_Event[Event]

func (x *Event) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Event.WeaverMarshal: nil receiver"))
	}
	enc.String(x.ID)
	enc.String(x.SourceType)
	enc.String(x.SourceID)
	enc.String(x.Title)
	enc.String(x.Description)
	enc.String(x.Category)
	enc.EncodeBinaryMarshaler(&x.EndTime)
	enc.EncodeBinaryMarshaler(&x.ResolutionTime)
	enc.String(x.Status)
	servicetwill_enc_ptr_string_3e89801b(enc, x.Outcome)
	enc.EncodeBinaryMarshaler(&x.CreatedAt)
	enc.EncodeBinaryMarshaler(&x.UpdatedAt)
}

func (x *Event) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Event.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.String()
	x.SourceType = dec.String()
	x.SourceID = dec.String()
	x.Title = dec.String()
	x.Description = dec.String()
	x.Category = dec.String()
	dec.DecodeBinaryUnmarshaler(&x.EndTime)
	dec.DecodeBinaryUnmarshaler(&x.ResolutionTime)
	x.Status = dec.String()
	x.Outcome = servicetwill_dec_ptr_string_3e89801b(dec)
	dec.DecodeBinaryUnmarshaler(&x.CreatedAt)
	dec.DecodeBinaryUnmarshaler(&x.UpdatedAt)
}

func servicetwill_enc_ptr_string_3e89801b(enc *codegen.Encoder, arg *string) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.String(*arg)
	}
}

func servicetwill_dec_ptr_string_3e89801b(dec *codegen.Decoder) *string {
	if !dec.Bool() {
		return nil
	}
	var res string
	res = dec.String()
	return &res
}

var _ codegen.AutoMarshal = (*ExchangeRate)(nil)

type __is_ExchangeRate[T ~struct {
	twill.AutoMarshal
	ID           string    "json:\"id\""
	FromCurrency string    "json:\"from_currency\""
	ToCurrency   string    "json:\"to_currency\""
	Rate         float64   "json:\"rate\""
	Provider     string    "json:\"provider\""
	Timestamp    time.Time "json:\"timestamp\""
}] struct{}

var _ __is_ExchangeRate[ExchangeRate]

func (x *ExchangeRate) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("ExchangeRate.WeaverMarshal: nil receiver"))
	}
	enc.String(x.ID)
	enc.String(x.FromCurrency)
	enc.String(x.ToCurrency)
	enc.Float64(x.Rate)
	enc.String(x.Provider)
	enc.EncodeBinaryMarshaler(&x.Timestamp)
}

func (x *ExchangeRate) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("ExchangeRate.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.String()
	x.FromCurrency = dec.String()
	x.ToCurrency = dec.String()
	x.Rate = dec.Float64()
	x.Provider = dec.String()
	dec.DecodeBinaryUnmarshaler(&x.Timestamp)
}

var _ codegen.AutoMarshal = (*Market)(nil)

type __is_Market[T ~struct {
	twill.AutoMarshal
	ID              string     "json:\"id\""
	MerchantID      string     "json:\"merchant_id\""
	EventID         string     "json:\"event_id\""
	Type            string     "json:\"type\""
	Question        string     "json:\"question\""
	Options         []string   "json:\"options\""
	Status          string     "json:\"status\""
	TotalVolume     float64    "json:\"total_volume\""
	LiquidityPool   float64    "json:\"liquidity_pool\""
	MerchantFeeRate float64    "json:\"-\""
	PlatformFeeRate float64    "json:\"-\""
	CreatedAt       time.Time  "json:\"created_at\""
	SettledAt       *time.Time "json:\"settled_at,omitempty\""
}] struct{}

var _ __is_Market[Market]

func (x *Market) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Market.WeaverMarshal: nil receiver"))
	}
	enc.String(x.ID)
	enc.String(x.MerchantID)
	enc.String(x.EventID)
	enc.String(x.Type)
	enc.String(x.Question)
	servicetwill_enc_slice_string_4af10117(enc, x.Options)
	enc.String(x.Status)
	enc.Float64(x.TotalVolume)
	enc.Float64(x.LiquidityPool)
	enc.Float64(x.MerchantFeeRate)
	enc.Float64(x.PlatformFeeRate)
	enc.EncodeBinaryMarshaler(&x.CreatedAt)
	servicetwill_enc_ptr_Time_7d81a94d(enc, x.SettledAt)
}

func (x *Market) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Market.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.String()
	x.MerchantID = dec.String()
	x.EventID = dec.String()
	x.Type = dec.String()
	x.Question = dec.String()
	x.Options = servicetwill_dec_slice_string_4af10117(dec)
	x.Status = dec.String()
	x.TotalVolume = dec.Float64()
	x.LiquidityPool = dec.Float64()
	x.MerchantFeeRate = dec.Float64()
	x.PlatformFeeRate = dec.Float64()
	dec.DecodeBinaryUnmarshaler(&x.CreatedAt)
	x.SettledAt = servicetwill_dec_ptr_Time_7d81a94d(dec)
}

func servicetwill_enc_slice_string_4af10117(enc *codegen.Encoder, arg []string) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for i := 0; i < len(arg); i++ {
		enc.String(arg[i])
	}
}

func servicetwill_dec_slice_string_4af10117(dec *codegen.Decoder) []string {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make([]string, n)
	for i := 0; i < n; i++ {
		res[i] = dec.String()
	}
	return res
}

func servicetwill_enc_ptr_Time_7d81a94d(enc *codegen.Encoder, arg *time.Time) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeBinaryMarshaler(arg)
	}
}

func servicetwill_dec_ptr_Time_7d81a94d(dec *codegen.Decoder) *time.Time {
	if !dec.Bool() {
		return nil
	}
	var res time.Time
	dec.DecodeBinaryUnmarshaler(&res)
	return &res
}

var _ codegen.AutoMarshal = (*Merchant)(nil)

type __is_Merchant[T ~struct {
	twill.AutoMarshal
	ID                          string     "json:\"id\""
	Name                        string     "json:\"name\""
	Email                       string     "json:\"email\""
	APIKey                      string     "json:\"api_key\""
	APIKeyPrefix                string     "json:\"-\""
	APISecret                   string     "json:\"-\""
	APISecretEncrypted          string     "json:\"-\""
	APISecretSecondaryEncrypted string     "json:\"-\""
	APISecretSecondaryExpiresAt *time.Time "json:\"-\""
	Status                      string     "json:\"status\""
	Currency                    string     "json:\"currency\""
	Timezone                    string     "json:\"timezone\""
	WalletMode                  string     "json:\"wallet_mode\""
	CallbackURL                 string     "json:\"-\""
	CallbackSecret              string     "json:\"-\""
	CallbackSecretEncrypted     string     "json:\"-\""
	WebhookURL                  string     "json:\"-\""
	WebhookEvents               []string   "json:\"-\""
	AllowedIPs                  []string   "json:\"-\""
	FeeRate                     float64    "json:\"-\""
	SeamlessDegraded            bool       "json:\"-\""
	CallbackVerifiedAt          *time.Time "json:\"-\""
	CreatedAt                   time.Time  "json:\"created_at\""
	UpdatedAt                   time.Time  "json:\"updated_at\""
}] struct{}

var _ __is_Merchant[Merchant]

func (x *Merchant) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Merchant.WeaverMarshal: nil receiver"))
	}
	enc.String(x.ID)
	enc.String(x.Name)
	enc.String(x.Email)
	enc.String(x.APIKey)
	enc.String(x.APIKeyPrefix)
	enc.String(x.APISecret)
	enc.String(x.APISecretEncrypted)
	enc.String(x.APISecretSecondaryEncrypted)
	servicetwill_enc_ptr_Time_7d81a94d(enc, x.APISecretSecondaryExpiresAt)
	enc.String(x.Status)
	enc.String(x.Currency)
	enc.String(x.Timezone)
	enc.String(x.WalletMode)
	enc.String(x.CallbackURL)
	enc.String(x.CallbackSecret)
	enc.String(x.CallbackSecretEncrypted)
	enc.String(x.WebhookURL)
	servicetwill_enc_slice_string_4af10117(enc, x.WebhookEvents)
	servicetwill_enc_slice_string_4af10117(enc, x.AllowedIPs)
	enc.Float64(x.FeeRate)
	enc.Bool(x.SeamlessDegraded)
	servicetwill_enc_ptr_Time_7d81a94d(enc, x.CallbackVerifiedAt)
	enc.EncodeBinaryMarshaler(&x.CreatedAt)
	enc.EncodeBinaryMarshaler(&x.UpdatedAt)
}

func (x *Merchant) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Merchant.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.String()
	x.Name = dec.String()
	x.Email = dec.String()
	x.APIKey = dec.String()
	x.APIKeyPrefix = dec.String()
	x.APISecret = dec.String()
	x.APISecretEncrypted = dec.String()
	x.APISecretSecondaryEncrypted = dec.String()
	x.APISecretSecondaryExpiresAt = servicetwill_dec_ptr_Time_7d81a94d(dec)
	x.Status = dec.String()
	x.Currency = dec.String()
	x.Timezone = dec.String()
	x.WalletMode = dec.String()
	x.CallbackURL = dec.String()
	x.CallbackSecret = dec.String()
	x.CallbackSecretEncrypted = dec.String()
	x.WebhookURL = dec.String()
	x.WebhookEvents = servicetwill_dec_slice_string_4af10117(dec)
	x.AllowedIPs = servicetwill_dec_slice_string_4af10117(dec)
	x.FeeRate = dec.Float64()
	x.SeamlessDegraded = dec.Bool()
	x.CallbackVerifiedAt = servicetwill_dec_ptr_Time_7d81a94d(dec)
	dec.DecodeBinaryUnmarshaler(&x.CreatedAt)
	dec.DecodeBinaryUnmarshaler(&x.UpdatedAt)
}

var _ codegen.AutoMarshal = (*Order)(nil)

type __is_Order[T ~struct {
	twill.AutoMarshal
	ID             string     "json:\"id\""
	MerchantID     string     "json:\"merchant_id\""
	UserID         string     "json:\"user_id\""
	MarketID       string     "json:\"market_id\""
	Type           string     "json:\"type\""
	Option         string     "json:\"option\""
	Amount         float64    "json:\"amount\""
	FilledAmount   float64    "json:\"filled_amount\""
	Currency       string     "json:\"currency\""
	Price          float64    "json:\"price\""
	TimeInForce    string     "json:\"time_in_force\""
	WalletKind     string     "json:\"-\""
	Channel        string     "json:\"-\""
	Status         string     "json:\"status\""
	IdempotencyKey string     "json:\"-\""
	CreatedAt      time.Time  "json:\"created_at\""
	FilledAt       *time.Time "json:\"filled_at,omitempty\""
}] struct{}

var _ __is_Order[Order]

func (x *Order) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Order.WeaverMarshal: nil receiver"))
	}
	enc.String(x.ID)
	enc.String(x.MerchantID)
	enc.String(x.UserID)
	enc.String(x.MarketID)
	enc.String(x.Type)
	enc.String(x.Option)
	enc.Float64(x.Amount)
	enc.Float64(x.FilledAmount)
	enc.String(x.Currency)
	enc.Float64(x.Price)
	enc.String(x.TimeInForce)
	enc.String(x.WalletKind)
	enc.String(x.Channel)
	enc.String(x.Status)
	enc.String(x.IdempotencyKey)
	enc.EncodeBinaryMarshaler(&x.CreatedAt)
	servicetwill_enc_ptr_Time_7d81a94d(enc, x.FilledAt)
}

func (x *Order) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Order.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.String()
	x.MerchantID = dec.String()
	x.UserID = dec.String()
	x.MarketID = dec.String()
	x.Type = dec.String()
	x.Option = dec.String()
	x.Amount = dec.Float64()
	x.FilledAmount = dec.Float64()
	x.Currency = dec.String()
	x.Price = dec.Float64()
	x.TimeInForce = dec.String()
	x.WalletKind = dec.String()
	x.Channel = dec.String()
	x.Status = dec.String()
	x.IdempotencyKey = dec.String()
	dec.DecodeBinaryUnmarshaler(&x.CreatedAt)
	x.FilledAt = servicetwill_dec_ptr_Time_7d81a94d(dec)
}

var _ codegen.AutoMarshal = (*Trade)(nil)

type __is_Trade[T ~struct {
	twill.AutoMarshal
	ID           string    "json:\"id\""
	MarketID     string    "json:\"market_id\""
	MakerOrderID string    "json:\"maker_order_id\""
	TakerOrderID string    "json:\"taker_order_id\""
	Shares       float64   "json:\"shares\""
	MatchedPrice float64   "json:\"matched_price\""
	CreatedAt    time.Time "json:\"created_at\""
}] struct{}

var _ __is_Trade[Trade]

func (x *Trade) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Trade.WeaverMarshal: nil receiver"))
	}
	enc.String(x.ID)
	enc.String(x.MarketID)
	enc.String(x.MakerOrderID)
	enc.String(x.TakerOrderID)
	enc.Float64(x.Shares)
	enc.Float64(x.MatchedPrice)
	enc.EncodeBinaryMarshaler(&x.CreatedAt)
}

func (x *Trade) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Trade.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.String()
	x.MarketID = dec.String()
	x.MakerOrderID = dec.String()
	x.TakerOrderID = dec.String()
	x.Shares = dec.Float64()
	x.MatchedPrice = dec.Float64()
	dec.DecodeBinaryUnmarshaler(&x.CreatedAt)
}

var _ codegen.AutoMarshal = (*Transaction)(nil)

type __is_Transaction[T ~struct {
	twill.AutoMarshal
	ID             string    "json:\"id\""
	WalletID       string    "json:\"wallet_id\""
	Type           string    "json:\"type\""
	Amount         float64   "json:\"amount\""
	Currency       string    "json:\"currency\""
	RelatedOrderID *string   "json:\"related_order_id,omitempty\""
	IdempotencyKey string    "json:\"-\""
	Status         string    "json:\"status\""
	CreatedAt      time.Time "json:\"created_at\""
}] struct{}

var _ __is_Transaction[Transaction]

func (x *Transaction) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Transaction.WeaverMarshal: nil receiver"))
	}
	enc.String(x.ID)
	enc.String(x.WalletID)
	enc.String(x.Type)
	enc.Float64(x.Amount)
	enc.String(x.Currency)
	servicetwill_enc_ptr_string_3e89801b(enc, x.RelatedOrderID)
	enc.String(x.IdempotencyKey)
	enc.String(x.Status)
	enc.EncodeBinaryMarshaler(&x.CreatedAt)
}

func (x *Transaction) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Transaction.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.String()
	x.WalletID = dec.String()
	x.Type = dec.String()
	x.Amount = dec.Float64()
	x.Currency = dec.String()
	x.RelatedOrderID = servicetwill_dec_ptr_string_3e89801b(dec)
	x.IdempotencyKey = dec.String()
	x.Status = dec.String()
	dec.DecodeBinaryUnmarshaler(&x.CreatedAt)
}

var _ codegen.AutoMarshal = (*Wallet)(nil)

type __is_Wallet[T ~struct {
	twill.AutoMarshal
	ID            string    "json:\"id\""
	MerchantID    string    "json:\"merchant_id\""
	UserID        string    "json:\"user_id\""
	Currency      string    "json:\"currency\""
	Kind          string    "json:\"kind\""
	Balance       float64   "json:\"balance\""
	LockedBalance float64   "json:\"locked_balance\""
	UpdatedAt     time.Time "json:\"updated_at\""
}] struct{}

var _ __is_Wallet[Wallet]

func (x *Wallet) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Wallet.WeaverMarshal: nil receiver"))
	}
	enc.String(x.ID)
	enc.String(x.MerchantID)
	enc.String(x.UserID)
	enc.String(x.Currency)
	enc.String(x.Kind)
	enc.Float64(x.Balance)
	enc.Float64(x.LockedBalance)
	enc.EncodeBinaryMarshaler(&x.UpdatedAt)
}

func (x *Wallet) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Wallet.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.String()
	x.MerchantID = dec.String()
	x.UserID = dec.String()
	x.Currency = dec.String()
	x.Kind = dec.String()
	x.Balance = dec.Float64()
	x.LockedBalance = dec.Float64()
	dec.DecodeBinaryUnmarshaler(&x.UpdatedAt)
}
