// Code generated by "twill generate". DO NOT EDIT.
//go:build !ignoreTwillGen

package wallet

import (
	"context"
	"errors"
	"github.com/afun-game/predictmarket-saas/pkg/types"
	"github.com/nxsky/twill"
	"github.com/nxsky/twill/runtime/codegen"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "github.com/afun-game/predictmarket-saas/internal/wallet/Service",
		Iface: reflect.TypeOf((*Service)(nil)).Elem(),
		Impl:  reflect.TypeOf(implementation{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return service_local_stub{impl: impl.(Service), tracer: tracer, createMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/wallet/Service", Method: "Create", Remote: false, Generated: true}), creditMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/wallet/Service", Method: "Credit", Remote: false, Generated: true}), creditWithIdempotencyMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/wallet/Service", Method: "CreditWithIdempotency", Remote: false, Generated: true}), debitMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/wallet/Service", Method: "Debit", Remote: false, Generated: true}), getMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/wallet/Service", Method: "Get", Remote: false, Generated: true}), getBalanceMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/wallet/Service", Method: "GetBalance", Remote: false, Generated: true}), listTransactionsMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/wallet/Service", Method: "ListTransactions", Remote: false, Generated: true}), lockMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/wallet/Service", Method: "Lock", Remote: false, Generated: true}), unlockMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/wallet/Service", Method: "Unlock", Remote: false, Generated: true})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return service_client_stub{stub: stub, createMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/wallet/Service", Method: "Create", Remote: true, Generated: true}), creditMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/wallet/Service", Method: "Credit", Remote: true, Generated: true}), creditWithIdempotencyMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/wallet/Service", Method: "CreditWithIdempotency", Remote: true, Generated: true}), debitMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/wallet/Service", Method: "Debit", Remote: true, Generated: true}), getMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/wallet/Service", Method: "Get", Remote: true, Generated: true}), getBalanceMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/wallet/Service", Method: "GetBalance", Remote: true, Generated: true}), listTransactionsMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/wallet/Service", Method: "ListTransactions", Remote: true, Generated: true}), lockMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/wallet/Service", Method: "Lock", Remote: true, Generated: true}), unlockMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/wallet/Service", Method: "Unlock", Remote: true, Generated: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return service_server_stub{impl: impl.(Service), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return service_reflect_stub{caller: caller}
		},
		RefData: "",
	})
}

// twill.InstanceOf checks.
var _ twill.InstanceOf[Service] = (*implementation)(nil)

// twill.Router checks.
var _ twill.Unrouted = (*implementation)(nil)

// Local stub implementations.

type service_local_stub struct {
	impl                         Service
	tracer                       trace.Tracer
	createMetrics                *codegen.MethodMetrics
	creditMetrics                *codegen.MethodMetrics
	creditWithIdempotencyMetrics *codegen.MethodMetrics
	debitMetrics                 *codegen.MethodMetrics
	getMetrics                   *codegen.MethodMetrics
	getBalanceMetrics            *codegen.MethodMetrics
	listTransactionsMetrics      *codegen.MethodMetrics
	lockMetrics                  *codegen.MethodMetrics
	unlockMetrics                *codegen.MethodMetrics
}

// Check that service_local_stub implements the Service interface.
var _ Service = (*service_local_stub)(nil)

func (s service_local_stub) Create(ctx context.Context, a0 string, a1 string, a2 string) (r0 *types.Wallet, err error) {
	// Update metrics.
	begin := s.createMetrics.Begin()
	defer func() { s.createMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "wallet.Service.Create", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Create(ctx, a0, a1, a2)
}

func (s service_local_stub) Credit(ctx context.Context, a0 string, a1 string, a2 string, a3 float64, a4 string) (err error) {
	// Update metrics.
	begin := s.creditMetrics.Begin()
	defer func() { s.creditMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "wallet.Service.Credit", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Credit(ctx, a0, a1, a2, a3, a4)
}

func (s service_local_stub) CreditWithIdempotency(ctx context.Context, a0 string, a1 string, a2 string, a3 float64, a4 string, a5 string) (err error) {
	// Update metrics.
	begin := s.creditWithIdempotencyMetrics.Begin()
	defer func() { s.creditWithIdempotencyMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "wallet.Service.CreditWithIdempotency", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.CreditWithIdempotency(ctx, a0, a1, a2, a3, a4, a5)
}

func (s service_local_stub) Debit(ctx context.Context, a0 string, a1 string, a2 string, a3 float64, a4 string) (err error) {
	// Update metrics.
	begin := s.debitMetrics.Begin()
	defer func() { s.debitMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "wallet.Service.Debit", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Debit(ctx, a0, a1, a2, a3, a4)
}

func (s service_local_stub) Get(ctx context.Context, a0 string, a1 string, a2 string) (r0 *types.Wallet, err error) {
	// Update metrics.
	begin := s.getMetrics.Begin()
	defer func() { s.getMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "wallet.Service.Get", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Get(ctx, a0, a1, a2)
}

func (s service_local_stub) GetBalance(ctx context.Context, a0 string, a1 string, a2 string) (r0 float64, r1 float64, err error) {
	// Update metrics.
	begin := s.getBalanceMetrics.Begin()
	defer func() { s.getBalanceMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "wallet.Service.GetBalance", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetBalance(ctx, a0, a1, a2)
}

func (s service_local_stub) ListTransactions(ctx context.Context, a0 string, a1 string, a2 int, a3 int) (r0 []*types.Transaction, r1 int, err error) {
	// Update metrics.
	begin := s.listTransactionsMetrics.Begin()
	defer func() { s.listTransactionsMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "wallet.Service.ListTransactions", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.ListTransactions(ctx, a0, a1, a2, a3)
}

func (s service_local_stub) Lock(ctx context.Context, a0 string, a1 string, a2 string, a3 float64) (err error) {
	// Update metrics.
	begin := s.lockMetrics.Begin()
	defer func() { s.lockMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "wallet.Service.Lock", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Lock(ctx, a0, a1, a2, a3)
}

func (s service_local_stub) Unlock(ctx context.Context, a0 string, a1 string, a2 string, a3 float64) (err error) {
	// Update metrics.
	begin := s.unlockMetrics.Begin()
	defer func() { s.unlockMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "wallet.Service.Unlock", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Unlock(ctx, a0, a1, a2, a3)
}

// Client stub implementations.

type service_client_stub struct {
	stub                         codegen.Stub
	createMetrics                *codegen.MethodMetrics
	creditMetrics                *codegen.MethodMetrics
	creditWithIdempotencyMetrics *codegen.MethodMetrics
	debitMetrics                 *codegen.MethodMetrics
	getMetrics                   *codegen.MethodMetrics
	getBalanceMetrics            *codegen.MethodMetrics
	listTransactionsMetrics      *codegen.MethodMetrics
	lockMetrics                  *codegen.MethodMetrics
	unlockMetrics                *codegen.MethodMetrics
}

// Check that service_client_stub implements the Service interface.
var _ Service = (*service_client_stub)(nil)

func (s service_client_stub) Create(ctx context.Context, a0 string, a1 string, a2 string) (r0 *types.Wallet, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.createMetrics.Begin()
	defer func() { s.createMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "wallet.Service.Create", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += (4 + len(a1))
	size += (4 + len(a2))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	enc.String(a1)
	enc.String(a2)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = servicetwill_dec_ptr_Wallet_d53e830d(dec)
	err = dec.Error()
	return
}

func (s service_client_stub) Credit(ctx context.Context, a0 string, a1 string, a2 string, a3 float64, a4 string) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.creditMetrics.Begin()
	defer func() { s.creditMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "wallet.Service.Credit", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += (4 + len(a1))
	size += (4 + len(a2))
	size += 8
	size += (4 + len(a4))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	enc.String(a1)
	enc.String(a2)
	enc.Float64(a3)
	enc.String(a4)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 1, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

func (s service_client_stub) CreditWithIdempotency(ctx context.Context, a0 string, a1 string, a2 string, a3 float64, a4 string, a5 string) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.creditWithIdempotencyMetrics.Begin()
	defer func() { s.creditWithIdempotencyMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "wallet.Service.CreditWithIdempotency", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += (4 + len(a1))
	size += (4 + len(a2))
	size += 8
	size += (4 + len(a4))
	size += (4 + len(a5))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	enc.String(a1)
	enc.String(a2)
	enc.Float64(a3)
	enc.String(a4)
	enc.String(a5)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 2, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

func (s service_client_stub) Debit(ctx context.Context, a0 string, a1 string, a2 string, a3 float64, a4 string) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.debitMetrics.Begin()
	defer func() { s.debitMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "wallet.Service.Debit", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += (4 + len(a1))
	size += (4 + len(a2))
	size += 8
	size += (4 + len(a4))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	enc.String(a1)
	enc.String(a2)
	enc.Float64(a3)
	enc.String(a4)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 3, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

func (s service_client_stub) Get(ctx context.Context, a0 string, a1 string, a2 string) (r0 *types.Wallet, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getMetrics.Begin()
	defer func() { s.getMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "wallet.Service.Get", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += (4 + len(a1))
	size += (4 + len(a2))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	enc.String(a1)
	enc.String(a2)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 4, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = servicetwill_dec_ptr_Wallet_d53e830d(dec)
	err = dec.Error()
	return
}

func (s service_client_stub) GetBalance(ctx context.Context, a0 string, a1 string, a2 string) (r0 float64, r1 float64, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getBalanceMetrics.Begin()
	defer func() { s.getBalanceMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "wallet.Service.GetBalance", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += (4 + len(a1))
	size += (4 + len(a2))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	enc.String(a1)
	enc.String(a2)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 5, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = dec.Float64()
	r1 = dec.Float64()
	err = dec.Error()
	return
}

func (s service_client_stub) ListTransactions(ctx context.Context, a0 string, a1 string, a2 int, a3 int) (r0 []*types.Transaction, r1 int, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.listTransactionsMetrics.Begin()
	defer func() { s.listTransactionsMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "wallet.Service.ListTransactions", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += (4 + len(a1))
	size += 8
	size += 8
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	enc.String(a1)
	enc.Int(a2)
	enc.Int(a3)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 6, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = servicetwill_dec_slice_ptr_Transaction_a3e08383(dec)
	r1 = dec.Int()
	err = dec.Error()
	return
}

func (s service_client_stub) Lock(ctx context.Context, a0 string, a1 string, a2 string, a3 float64) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.lockMetrics.Begin()
	defer func() { s.lockMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "wallet.Service.Lock", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += (4 + len(a1))
	size += (4 + len(a2))
	size += 8
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	enc.String(a1)
	enc.String(a2)
	enc.Float64(a3)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 7, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

func (s service_client_stub) Unlock(ctx context.Context, a0 string, a1 string, a2 string, a3 float64) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.unlockMetrics.Begin()
	defer func() { s.unlockMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "wallet.Service.Unlock", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += (4 + len(a1))
	size += (4 + len(a2))
	size += 8
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	enc.String(a1)
	enc.String(a2)
	enc.Float64(a3)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 8, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

// Note that "twill generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][24]struct{}](`

ERROR: You generated this file with 'twill generate' (devel) (codegen
version v0.24.0). The generated code is incompatible with the version of the
github.com/nxsky/twill module that you're using. The twill module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/nxsky/twill

We recommend updating the twill module and the 'twill generate' command by
running the following.

    go get github.com/nxsky/twill@latest
    go install github.com/nxsky/twill/cmd/twill@latest

Then, re-run 'twill generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/Twill/twill/issues.

`)

// Server stub implementations.

type service_server_stub struct {
	impl    Service
	addLoad func(key uint64, load float64)
}

// Check that service_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*service_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s service_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "Create":
		return s.create
	case "Credit":
		return s.credit
	case "CreditWithIdempotency":
		return s.creditWithIdempotency
	case "Debit":
		return s.debit
	case "Get":
		return s.get
	case "GetBalance":
		return s.getBalance
	case "ListTransactions":
		return s.listTransactions
	case "Lock":
		return s.lock
	case "Unlock":
		return s.unlock
	default:
		return nil
	}
}

func (s service_server_stub) create(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 string
	a1 = dec.String()
	var a2 string
	a2 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.Create(ctx, a0, a1, a2)

	// Encode the results.
	enc := codegen.NewEncoder()
	servicetwill_enc_ptr_Wallet_d53e830d(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) credit(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 string
	a1 = dec.String()
	var a2 string
	a2 = dec.String()
	var a3 float64
	a3 = dec.Float64()
	var a4 string
	a4 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.Credit(ctx, a0, a1, a2, a3, a4)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) creditWithIdempotency(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 string
	a1 = dec.String()
	var a2 string
	a2 = dec.String()
	var a3 float64
	a3 = dec.Float64()
	var a4 string
	a4 = dec.String()
	var a5 string
	a5 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.CreditWithIdempotency(ctx, a0, a1, a2, a3, a4, a5)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) debit(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 string
	a1 = dec.String()
	var a2 string
	a2 = dec.String()
	var a3 float64
	a3 = dec.Float64()
	var a4 string
	a4 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.Debit(ctx, a0, a1, a2, a3, a4)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) get(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 string
	a1 = dec.String()
	var a2 string
	a2 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.Get(ctx, a0, a1, a2)

	// Encode the results.
	enc := codegen.NewEncoder()
	servicetwill_enc_ptr_Wallet_d53e830d(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) getBalance(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 string
	a1 = dec.String()
	var a2 string
	a2 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, r1, appErr := s.impl.GetBalance(ctx, a0, a1, a2)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Float64(r0)
	enc.Float64(r1)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) listTransactions(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 string
	a1 = dec.String()
	var a2 int
	a2 = dec.Int()
	var a3 int
	a3 = dec.Int()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, r1, appErr := s.impl.ListTransactions(ctx, a0, a1, a2, a3)

	// Encode the results.
	enc := codegen.NewEncoder()
	servicetwill_enc_slice_ptr_Transaction_a3e08383(enc, r0)
	enc.Int(r1)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) lock(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 string
	a1 = dec.String()
	var a2 string
	a2 = dec.String()
	var a3 float64
	a3 = dec.Float64()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.Lock(ctx, a0, a1, a2, a3)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) unlock(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 string
	a1 = dec.String()
	var a2 string
	a2 = dec.String()
	var a3 float64
	a3 = dec.Float64()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.Unlock(ctx, a0, a1, a2, a3)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

// Reflect stub implementations.

type service_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that service_reflect_stub implements the Service interface.
var _ Service = (*service_reflect_stub)(nil)

func (s service_reflect_stub) Create(ctx context.Context, a0 string, a1 string, a2 string) (r0 *types.Wallet, err error) {
	err = s.caller("Create", ctx, []any{a0, a1, a2}, []any{&r0})
	return
}

func (s service_reflect_stub) Credit(ctx context.Context, a0 string, a1 string, a2 string, a3 float64, a4 string) (err error) {
	err = s.caller("Credit", ctx, []any{a0, a1, a2, a3, a4}, []any{})
	return
}

func (s service_reflect_stub) CreditWithIdempotency(ctx context.Context, a0 string, a1 string, a2 string, a3 float64, a4 string, a5 string) (err error) {
	err = s.caller("CreditWithIdempotency", ctx, []any{a0, a1, a2, a3, a4, a5}, []any{})
	return
}

func (s service_reflect_stub) Debit(ctx context.Context, a0 string, a1 string, a2 string, a3 float64, a4 string) (err error) {
	err = s.caller("Debit", ctx, []any{a0, a1, a2, a3, a4}, []any{})
	return
}

func (s service_reflect_stub) Get(ctx context.Context, a0 string, a1 string, a2 string) (r0 *types.Wallet, err error) {
	err = s.caller("Get", ctx, []any{a0, a1, a2}, []any{&r0})
	return
}

func (s service_reflect_stub) GetBalance(ctx context.Context, a0 string, a1 string, a2 string) (r0 float64, r1 float64, err error) {
	err = s.caller("GetBalance", ctx, []any{a0, a1, a2}, []any{&r0, &r1})
	return
}

func (s service_reflect_stub) ListTransactions(ctx context.Context, a0 string, a1 string, a2 int, a3 int) (r0 []*types.Transaction, r1 int, err error) {
	err = s.caller("ListTransactions", ctx, []any{a0, a1, a2, a3}, []any{&r0, &r1})
	return
}

func (s service_reflect_stub) Lock(ctx context.Context, a0 string, a1 string, a2 string, a3 float64) (err error) {
	err = s.caller("Lock", ctx, []any{a0, a1, a2, a3}, []any{})
	return
}

func (s service_reflect_stub) Unlock(ctx context.Context, a0 string, a1 string, a2 string, a3 float64) (err error) {
	err = s.caller("Unlock", ctx, []any{a0, a1, a2, a3}, []any{})
	return
}

// Encoding/decoding implementations.

func servicetwill_enc_ptr_Wallet_d53e830d(enc *codegen.Encoder, arg *types.Wallet) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func servicetwill_dec_ptr_Wallet_d53e830d(dec *codegen.Decoder) *types.Wallet {
	if !dec.Bool() {
		return nil
	}
	var res types.Wallet
	(&res).WeaverUnmarshal(dec)
	return &res
}

func servicetwill_enc_ptr_Transaction_f020bb45(enc *codegen.Encoder, arg *types.Transaction) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func servicetwill_dec_ptr_Transaction_f020bb45(dec *codegen.Decoder) *types.Transaction {
	if !dec.Bool() {
		return nil
	}
	var res types.Transaction
	(&res).WeaverUnmarshal(dec)
	return &res
}

func servicetwill_enc_slice_ptr_Transaction_a3e08383(enc *codegen.Encoder, arg []*types.Transaction) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for i := 0; i < len(arg); i++ {
		servicetwill_enc_ptr_Transaction_f020bb45(enc, arg[i])
	}
}

func servicetwill_dec_slice_ptr_Transaction_a3e08383(dec *codegen.Decoder) []*types.Transaction {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make([]*types.Transaction, n)
	for i := 0; i < n; i++ {
		res[i] = servicetwill_dec_ptr_Transaction_f020bb45(dec)
	}
	return res
}
