apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: predictmarket-dev
resources:
  - configmap.yaml
  - redis.yaml
  - nats.yaml
  - api.yaml
  - ingress.yaml
  - migration-job.yaml
