// Code generated by "twill generate". DO NOT EDIT.
//go:build !ignoreTwillGen

package analytics

import (
	"context"
	"errors"
	"fmt"
	"github.com/nxsky/twill"
	"github.com/nxsky/twill/runtime/codegen"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "github.com/afun-game/predictmarket-saas/internal/analytics/Service",
		Iface: reflect.TypeOf((*Service)(nil)).Elem(),
		Impl:  reflect.TypeOf(implementation{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return service_local_stub{impl: impl.(Service), tracer: tracer, getMarketStatsMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/analytics/Service", Method: "GetMarketStats", Remote: false, Generated: true}), getMerchantStatsMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/analytics/Service", Method: "GetMerchantStats", Remote: false, Generated: true}), getPlatformStatsMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/analytics/Service", Method: "GetPlatformStats", Remote: false, Generated: true}), getUserStatsMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/analytics/Service", Method: "GetUserStats", Remote: false, Generated: true})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return service_client_stub{stub: stub, getMarketStatsMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/analytics/Service", Method: "GetMarketStats", Remote: true, Generated: true}), getMerchantStatsMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/analytics/Service", Method: "GetMerchantStats", Remote: true, Generated: true}), getPlatformStatsMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/analytics/Service", Method: "GetPlatformStats", Remote: true, Generated: true}), getUserStatsMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/analytics/Service", Method: "GetUserStats", Remote: true, Generated: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return service_server_stub{impl: impl.(Service), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return service_reflect_stub{caller: caller}
		},
		RefData: "",
	})
}

// twill.InstanceOf checks.
var _ twill.InstanceOf[Service] = (*implementation)(nil)

// twill.Router checks.
var _ twill.Unrouted = (*implementation)(nil)

// Local stub implementations.

type service_local_stub struct {
	impl                    Service
	tracer                  trace.Tracer
	getMarketStatsMetrics   *codegen.MethodMetrics
	getMerchantStatsMetrics *codegen.MethodMetrics
	getPlatformStatsMetrics *codegen.MethodMetrics
	getUserStatsMetrics     *codegen.MethodMetrics
}

// Check that service_local_stub implements the Service interface.
var _ Service = (*service_local_stub)(nil)

func (s service_local_stub) GetMarketStats(ctx context.Context, a0 string) (r0 *MarketStats, err error) {
	// Update metrics.
	begin := s.getMarketStatsMetrics.Begin()
	defer func() { s.getMarketStatsMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "analytics.Service.GetMarketStats", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetMarketStats(ctx, a0)
}

func (s service_local_stub) GetMerchantStats(ctx context.Context, a0 string, a1 string) (r0 *MerchantStats, err error) {
	// Update metrics.
	begin := s.getMerchantStatsMetrics.Begin()
	defer func() { s.getMerchantStatsMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "analytics.Service.GetMerchantStats", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetMerchantStats(ctx, a0, a1)
}

func (s service_local_stub) GetPlatformStats(ctx context.Context, a0 string) (r0 *PlatformStats, err error) {
	// Update metrics.
	begin := s.getPlatformStatsMetrics.Begin()
	defer func() { s.getPlatformStatsMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "analytics.Service.GetPlatformStats", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetPlatformStats(ctx, a0)
}

func (s service_local_stub) GetUserStats(ctx context.Context, a0 string, a1 string) (r0 *UserStats, err error) {
	// Update metrics.
	begin := s.getUserStatsMetrics.Begin()
	defer func() { s.getUserStatsMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "analytics.Service.GetUserStats", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetUserStats(ctx, a0, a1)
}

// Client stub implementations.

type service_client_stub struct {
	stub                    codegen.Stub
	getMarketStatsMetrics   *codegen.MethodMetrics
	getMerchantStatsMetrics *codegen.MethodMetrics
	getPlatformStatsMetrics *codegen.MethodMetrics
	getUserStatsMetrics     *codegen.MethodMetrics
}

// Check that service_client_stub implements the Service interface.
var _ Service = (*service_client_stub)(nil)

func (s service_client_stub) GetMarketStats(ctx context.Context, a0 string) (r0 *MarketStats, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getMarketStatsMetrics.Begin()
	defer func() { s.getMarketStatsMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "analytics.Service.GetMarketStats", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = servicetwill_dec_ptr_MarketStats_1447bda7(dec)
	err = dec.Error()
	return
}

func (s service_client_stub) GetMerchantStats(ctx context.Context, a0 string, a1 string) (r0 *MerchantStats, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getMerchantStatsMetrics.Begin()
	defer func() { s.getMerchantStatsMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "analytics.Service.GetMerchantStats", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += (4 + len(a1))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	enc.String(a1)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 1, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = servicetwill_dec_ptr_MerchantStats_dc8ff5c0(dec)
	err = dec.Error()
	return
}

func (s service_client_stub) GetPlatformStats(ctx context.Context, a0 string) (r0 *PlatformStats, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getPlatformStatsMetrics.Begin()
	defer func() { s.getPlatformStatsMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "analytics.Service.GetPlatformStats", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 2, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = servicetwill_dec_ptr_PlatformStats_1bd851b7(dec)
	err = dec.Error()
	return
}

func (s service_client_stub) GetUserStats(ctx context.Context, a0 string, a1 string) (r0 *UserStats, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getUserStatsMetrics.Begin()
	defer func() { s.getUserStatsMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "analytics.Service.GetUserStats", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += (4 + len(a1))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	enc.String(a1)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 3, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = servicetwill_dec_ptr_UserStats_26f88613(dec)
	err = dec.Error()
	return
}

// Note that "twill generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][24]struct{}](`

ERROR: You generated this file with 'twill generate' v0.24.7 (codegen
version v0.24.0). The generated code is incompatible with the version of the
github.com/nxsky/twill module that you're using. The twill module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/nxsky/twill

We recommend updating the twill module and the 'twill generate' command by
running the following.

    go get github.com/nxsky/twill@latest
    go install github.com/nxsky/twill/cmd/twill@latest

Then, re-run 'twill generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/Twill/twill/issues.

`)

// Server stub implementations.

type service_server_stub struct {
	impl    Service
	addLoad func(key uint64, load float64)
}

// Check that service_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*service_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s service_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "GetMarketStats":
		return s.getMarketStats
	case "GetMerchantStats":
		return s.getMerchantStats
	case "GetPlatformStats":
		return s.getPlatformStats
	case "GetUserStats":
		return s.getUserStats
	default:
		return nil
	}
}

func (s service_server_stub) getMarketStats(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetMarketStats(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	servicetwill_enc_ptr_MarketStats_1447bda7(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) getMerchantStats(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 string
	a1 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetMerchantStats(ctx, a0, a1)

	// Encode the results.
	enc := codegen.NewEncoder()
	servicetwill_enc_ptr_MerchantStats_dc8ff5c0(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) getPlatformStats(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetPlatformStats(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	servicetwill_enc_ptr_PlatformStats_1bd851b7(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) getUserStats(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 string
	a1 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetUserStats(ctx, a0, a1)

	// Encode the results.
	enc := codegen.NewEncoder()
	servicetwill_enc_ptr_UserStats_26f88613(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

// Reflect stub implementations.

type service_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that service_reflect_stub implements the Service interface.
var _ Service = (*service_reflect_stub)(nil)

func (s service_reflect_stub) GetMarketStats(ctx context.Context, a0 string) (r0 *MarketStats, err error) {
	err = s.caller("GetMarketStats", ctx, []any{a0}, []any{&r0})
	return
}

func (s service_reflect_stub) GetMerchantStats(ctx context.Context, a0 string, a1 string) (r0 *MerchantStats, err error) {
	err = s.caller("GetMerchantStats", ctx, []any{a0, a1}, []any{&r0})
	return
}

func (s service_reflect_stub) GetPlatformStats(ctx context.Context, a0 string) (r0 *PlatformStats, err error) {
	err = s.caller("GetPlatformStats", ctx, []any{a0}, []any{&r0})
	return
}

func (s service_reflect_stub) GetUserStats(ctx context.Context, a0 string, a1 string) (r0 *UserStats, err error) {
	err = s.caller("GetUserStats", ctx, []any{a0, a1}, []any{&r0})
	return
}

// AutoMarshal implementations.

var _ codegen.AutoMarshal = (*MarketStats)(nil)

type __is_MarketStats[T ~struct {
	twill.AutoMarshal
	TotalVolume   float64            "json:\"total_volume\""
	TotalOrders   int64              "json:\"total_orders\""
	UniqueTraders int64              "json:\"unique_traders\""
	PriceHistory  []PricePoint       "json:\"price_history\""
	Distribution  map[string]float64 "json:\"distribution\""
}] struct{}

var _ __is_MarketStats[MarketStats]

func (x *MarketStats) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("MarketStats.WeaverMarshal: nil receiver"))
	}
	enc.Float64(x.TotalVolume)
	enc.Int64(x.TotalOrders)
	enc.Int64(x.UniqueTraders)
	servicetwill_enc_slice_PricePoint_95441832(enc, x.PriceHistory)
	servicetwill_enc_map_string_float64_640cfc19(enc, x.Distribution)
}

func (x *MarketStats) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("MarketStats.WeaverUnmarshal: nil receiver"))
	}
	x.TotalVolume = dec.Float64()
	x.TotalOrders = dec.Int64()
	x.UniqueTraders = dec.Int64()
	x.PriceHistory = servicetwill_dec_slice_PricePoint_95441832(dec)
	x.Distribution = servicetwill_dec_map_string_float64_640cfc19(dec)
}

func servicetwill_enc_slice_PricePoint_95441832(enc *codegen.Encoder, arg []PricePoint) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for i := 0; i < len(arg); i++ {
		(arg[i]).WeaverMarshal(enc)
	}
}

func servicetwill_dec_slice_PricePoint_95441832(dec *codegen.Decoder) []PricePoint {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make([]PricePoint, n)
	for i := 0; i < n; i++ {
		(&res[i]).WeaverUnmarshal(dec)
	}
	return res
}

func servicetwill_enc_map_string_float64_640cfc19(enc *codegen.Encoder, arg map[string]float64) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for k, v := range arg {
		enc.String(k)
		enc.Float64(v)
	}
}

func servicetwill_dec_map_string_float64_640cfc19(dec *codegen.Decoder) map[string]float64 {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make(map[string]float64, n)
	var k string
	var v float64
	for i := 0; i < n; i++ {
		k = dec.String()
		v = dec.Float64()
		res[k] = v
	}
	return res
}

var _ codegen.AutoMarshal = (*MerchantStats)(nil)

type __is_MerchantStats[T ~struct {
	twill.AutoMarshal
	TotalVolume       float64            "json:\"total_volume\""
	VolumeByCurrency  map[string]float64 "json:\"volume_by_currency\""
	TotalOrders       int64              "json:\"total_orders\""
	ActiveMarkets     int64              "json:\"active_markets\""
	ActiveUsers       int64              "json:\"active_users\""
	RevenueFromFee    float64            "json:\"revenue_from_fee\""
	RevenueByCurrency map[string]float64 "json:\"revenue_by_currency\""
}] struct{}

var _ __is_MerchantStats[MerchantStats]

func (x *MerchantStats) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("MerchantStats.WeaverMarshal: nil receiver"))
	}
	enc.Float64(x.TotalVolume)
	servicetwill_enc_map_string_float64_640cfc19(enc, x.VolumeByCurrency)
	enc.Int64(x.TotalOrders)
	enc.Int64(x.ActiveMarkets)
	enc.Int64(x.ActiveUsers)
	enc.Float64(x.RevenueFromFee)
	servicetwill_enc_map_string_float64_640cfc19(enc, x.RevenueByCurrency)
}

func (x *MerchantStats) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("MerchantStats.WeaverUnmarshal: nil receiver"))
	}
	x.TotalVolume = dec.Float64()
	x.VolumeByCurrency = servicetwill_dec_map_string_float64_640cfc19(dec)
	x.TotalOrders = dec.Int64()
	x.ActiveMarkets = dec.Int64()
	x.ActiveUsers = dec.Int64()
	x.RevenueFromFee = dec.Float64()
	x.RevenueByCurrency = servicetwill_dec_map_string_float64_640cfc19(dec)
}

var _ codegen.AutoMarshal = (*PlatformStats)(nil)

type __is_PlatformStats[T ~struct {
	twill.AutoMarshal
	TotalMerchants   int64              "json:\"total_merchants\""
	TotalMarkets     int64              "json:\"total_markets\""
	TotalVolume      float64            "json:\"total_volume\""
	VolumeByCurrency map[string]float64 "json:\"volume_by_currency\""
	TotalOrders      int64              "json:\"total_orders\""
}] struct{}

var _ __is_PlatformStats[PlatformStats]

func (x *PlatformStats) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("PlatformStats.WeaverMarshal: nil receiver"))
	}
	enc.Int64(x.TotalMerchants)
	enc.Int64(x.TotalMarkets)
	enc.Float64(x.TotalVolume)
	servicetwill_enc_map_string_float64_640cfc19(enc, x.VolumeByCurrency)
	enc.Int64(x.TotalOrders)
}

func (x *PlatformStats) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("PlatformStats.WeaverUnmarshal: nil receiver"))
	}
	x.TotalMerchants = dec.Int64()
	x.TotalMarkets = dec.Int64()
	x.TotalVolume = dec.Float64()
	x.VolumeByCurrency = servicetwill_dec_map_string_float64_640cfc19(dec)
	x.TotalOrders = dec.Int64()
}

var _ codegen.AutoMarshal = (*PricePoint)(nil)

type __is_PricePoint[T ~struct {
	twill.AutoMarshal
	Timestamp int64   "json:\"timestamp\""
	Price     float64 "json:\"price\""
}] struct{}

var _ __is_PricePoint[PricePoint]

func (x *PricePoint) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("PricePoint.WeaverMarshal: nil receiver"))
	}
	enc.Int64(x.Timestamp)
	enc.Float64(x.Price)
}

func (x *PricePoint) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("PricePoint.WeaverUnmarshal: nil receiver"))
	}
	x.Timestamp = dec.Int64()
	x.Price = dec.Float64()
}

var _ codegen.AutoMarshal = (*UserStats)(nil)

type __is_UserStats[T ~struct {
	twill.AutoMarshal
	TotalOrders      int64              "json:\"total_orders\""
	TotalVolume      float64            "json:\"total_volume\""
	VolumeByCurrency map[string]float64 "json:\"volume_by_currency\""
	WinRate          float64            "json:\"win_rate\""
	CurrentProfit    float64            "json:\"current_profit\""
	ProfitByCurrency map[string]float64 "json:\"profit_by_currency\""
}] struct{}

var _ __is_UserStats[UserStats]

func (x *UserStats) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("UserStats.WeaverMarshal: nil receiver"))
	}
	enc.Int64(x.TotalOrders)
	enc.Float64(x.TotalVolume)
	servicetwill_enc_map_string_float64_640cfc19(enc, x.VolumeByCurrency)
	enc.Float64(x.WinRate)
	enc.Float64(x.CurrentProfit)
	servicetwill_enc_map_string_float64_640cfc19(enc, x.ProfitByCurrency)
}

func (x *UserStats) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("UserStats.WeaverUnmarshal: nil receiver"))
	}
	x.TotalOrders = dec.Int64()
	x.TotalVolume = dec.Float64()
	x.VolumeByCurrency = servicetwill_dec_map_string_float64_640cfc19(dec)
	x.WinRate = dec.Float64()
	x.CurrentProfit = dec.Float64()
	x.ProfitByCurrency = servicetwill_dec_map_string_float64_640cfc19(dec)
}

// Encoding/decoding implementations.

func servicetwill_enc_ptr_MarketStats_1447bda7(enc *codegen.Encoder, arg *MarketStats) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func servicetwill_dec_ptr_MarketStats_1447bda7(dec *codegen.Decoder) *MarketStats {
	if !dec.Bool() {
		return nil
	}
	var res MarketStats
	(&res).WeaverUnmarshal(dec)
	return &res
}

func servicetwill_enc_ptr_MerchantStats_dc8ff5c0(enc *codegen.Encoder, arg *MerchantStats) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func servicetwill_dec_ptr_MerchantStats_dc8ff5c0(dec *codegen.Decoder) *MerchantStats {
	if !dec.Bool() {
		return nil
	}
	var res MerchantStats
	(&res).WeaverUnmarshal(dec)
	return &res
}

func servicetwill_enc_ptr_PlatformStats_1bd851b7(enc *codegen.Encoder, arg *PlatformStats) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func servicetwill_dec_ptr_PlatformStats_1bd851b7(dec *codegen.Decoder) *PlatformStats {
	if !dec.Bool() {
		return nil
	}
	var res PlatformStats
	(&res).WeaverUnmarshal(dec)
	return &res
}

func servicetwill_enc_ptr_UserStats_26f88613(enc *codegen.Encoder, arg *UserStats) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func servicetwill_dec_ptr_UserStats_26f88613(dec *codegen.Decoder) *UserStats {
	if !dec.Bool() {
		return nil
	}
	var res UserStats
	(&res).WeaverUnmarshal(dec)
	return &res
}
