// Code generated by "twill generate". DO NOT EDIT.
//go:build !ignoreTwillGen

package sports

import (
	"context"
	"errors"
	"fmt"
	"github.com/afun-game/predictmarket-saas/pkg/types"
	"github.com/nxsky/twill"
	"github.com/nxsky/twill/runtime/codegen"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
	"time"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "github.com/afun-game/predictmarket-saas/internal/sports/Service",
		Iface: reflect.TypeOf((*Service)(nil)).Elem(),
		Impl:  reflect.TypeOf(implementation{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return service_local_stub{impl: impl.(Service), tracer: tracer, getEventMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/sports/Service", Method: "GetEvent", Remote: false, Generated: true}), listEventsMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/sports/Service", Method: "ListEvents", Remote: false, Generated: true}), syncFromPolymarketMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/sports/Service", Method: "SyncFromPolymarket", Remote: false, Generated: true})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return service_client_stub{stub: stub, getEventMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/sports/Service", Method: "GetEvent", Remote: true, Generated: true}), listEventsMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/sports/Service", Method: "ListEvents", Remote: true, Generated: true}), syncFromPolymarketMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/afun-game/predictmarket-saas/internal/sports/Service", Method: "SyncFromPolymarket", Remote: true, Generated: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return service_server_stub{impl: impl.(Service), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return service_reflect_stub{caller: caller}
		},
		RefData: "⟦9f4688a3:wEaVeReDgE:github.com/afun-game/predictmarket-saas/internal/sports/Service→github.com/afun-game/predictmarket-saas/internal/event/Service⟧\n",
	})
}

// twill.InstanceOf checks.
var _ twill.InstanceOf[Service] = (*implementation)(nil)

// twill.Router checks.
var _ twill.Unrouted = (*implementation)(nil)

// Local stub implementations.

type service_local_stub struct {
	impl                      Service
	tracer                    trace.Tracer
	getEventMetrics           *codegen.MethodMetrics
	listEventsMetrics         *codegen.MethodMetrics
	syncFromPolymarketMetrics *codegen.MethodMetrics
}

// Check that service_local_stub implements the Service interface.
var _ Service = (*service_local_stub)(nil)

func (s service_local_stub) GetEvent(ctx context.Context, a0 string) (r0 *SportsEvent, err error) {
	// Update metrics.
	begin := s.getEventMetrics.Begin()
	defer func() { s.getEventMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "sports.Service.GetEvent", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetEvent(ctx, a0)
}

func (s service_local_stub) ListEvents(ctx context.Context, a0 *EventFilters) (r0 []*SportsEvent, r1 int, err error) {
	// Update metrics.
	begin := s.listEventsMetrics.Begin()
	defer func() { s.listEventsMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "sports.Service.ListEvents", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.ListEvents(ctx, a0)
}

func (s service_local_stub) SyncFromPolymarket(ctx context.Context) (err error) {
	// Update metrics.
	begin := s.syncFromPolymarketMetrics.Begin()
	defer func() { s.syncFromPolymarketMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "sports.Service.SyncFromPolymarket", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.SyncFromPolymarket(ctx)
}

// Client stub implementations.

type service_client_stub struct {
	stub                      codegen.Stub
	getEventMetrics           *codegen.MethodMetrics
	listEventsMetrics         *codegen.MethodMetrics
	syncFromPolymarketMetrics *codegen.MethodMetrics
}

// Check that service_client_stub implements the Service interface.
var _ Service = (*service_client_stub)(nil)

func (s service_client_stub) GetEvent(ctx context.Context, a0 string) (r0 *SportsEvent, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getEventMetrics.Begin()
	defer func() { s.getEventMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "sports.Service.GetEvent", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = servicetwill_dec_ptr_SportsEvent_93a527b6(dec)
	err = dec.Error()
	return
}

func (s service_client_stub) ListEvents(ctx context.Context, a0 *EventFilters) (r0 []*SportsEvent, r1 int, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.listEventsMetrics.Begin()
	defer func() { s.listEventsMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "sports.Service.ListEvents", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += servicetwill_size_ptr_EventFilters_e36df6d3(a0)
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	servicetwill_enc_ptr_EventFilters_e36df6d3(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 1, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = servicetwill_dec_slice_ptr_SportsEvent_61fee747(dec)
	r1 = dec.Int()
	err = dec.Error()
	return
}

func (s service_client_stub) SyncFromPolymarket(ctx context.Context) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.syncFromPolymarketMetrics.Begin()
	defer func() { s.syncFromPolymarketMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "sports.Service.SyncFromPolymarket", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(twill.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	var shardKey uint64

	// Call the remote method.
	var results []byte
	results, err = s.stub.Run(ctx, 2, nil, shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(twill.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

// Note that "twill generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][24]struct{}](`

ERROR: You generated this file with 'twill generate' v0.24.7 (codegen
version v0.24.0). The generated code is incompatible with the version of the
github.com/nxsky/twill module that you're using. The twill module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/nxsky/twill

We recommend updating the twill module and the 'twill generate' command by
running the following.

    go get github.com/nxsky/twill@latest
    go install github.com/nxsky/twill/cmd/twill@latest

Then, re-run 'twill generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/Twill/twill/issues.

`)

// Server stub implementations.

type service_server_stub struct {
	impl    Service
	addLoad func(key uint64, load float64)
}

// Check that service_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*service_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s service_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "GetEvent":
		return s.getEvent
	case "ListEvents":
		return s.listEvents
	case "SyncFromPolymarket":
		return s.syncFromPolymarket
	default:
		return nil
	}
}

func (s service_server_stub) getEvent(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetEvent(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	servicetwill_enc_ptr_SportsEvent_93a527b6(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) listEvents(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *EventFilters
	a0 = servicetwill_dec_ptr_EventFilters_e36df6d3(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, r1, appErr := s.impl.ListEvents(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	servicetwill_enc_slice_ptr_SportsEvent_61fee747(enc, r0)
	enc.Int(r1)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s service_server_stub) syncFromPolymarket(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.SyncFromPolymarket(ctx)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

// Reflect stub implementations.

type service_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that service_reflect_stub implements the Service interface.
var _ Service = (*service_reflect_stub)(nil)

func (s service_reflect_stub) GetEvent(ctx context.Context, a0 string) (r0 *SportsEvent, err error) {
	err = s.caller("GetEvent", ctx, []any{a0}, []any{&r0})
	return
}

func (s service_reflect_stub) ListEvents(ctx context.Context, a0 *EventFilters) (r0 []*SportsEvent, r1 int, err error) {
	err = s.caller("ListEvents", ctx, []any{a0}, []any{&r0, &r1})
	return
}

func (s service_reflect_stub) SyncFromPolymarket(ctx context.Context) (err error) {
	err = s.caller("SyncFromPolymarket", ctx, []any{}, []any{})
	return
}

// AutoMarshal implementations.

var _ codegen.AutoMarshal = (*EventFilters)(nil)

type __is_EventFilters[T ~struct {
	twill.AutoMarshal
	League string "json:\"league,omitempty\""
	Team   string "json:\"team,omitempty\""
	Status string "json:\"status,omitempty\""
	Page   int    "json:\"page,omitempty\""
	Limit  int    "json:\"limit,omitempty\""
}] struct{}

var _ __is_EventFilters[EventFilters]

func (x *EventFilters) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("EventFilters.WeaverMarshal: nil receiver"))
	}
	enc.String(x.League)
	enc.String(x.Team)
	enc.String(x.Status)
	enc.Int(x.Page)
	enc.Int(x.Limit)
}

func (x *EventFilters) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("EventFilters.WeaverUnmarshal: nil receiver"))
	}
	x.League = dec.String()
	x.Team = dec.String()
	x.Status = dec.String()
	x.Page = dec.Int()
	x.Limit = dec.Int()
}

var _ codegen.AutoMarshal = (*SportsEvent)(nil)

type __is_SportsEvent[T ~struct {
	twill.AutoMarshal
	Event     *types.Event "json:\"event\""
	League    string       "json:\"league\""
	GameID    string       "json:\"game_id,omitempty\""
	StartTime *time.Time   "json:\"start_time,omitempty\""
	Teams     []Team       "json:\"teams\""
}] struct{}

var _ __is_SportsEvent[SportsEvent]

func (x *SportsEvent) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("SportsEvent.WeaverMarshal: nil receiver"))
	}
	servicetwill_enc_ptr_Event_e8a4a956(enc, x.Event)
	enc.String(x.League)
	enc.String(x.GameID)
	servicetwill_enc_ptr_Time_7d81a94d(enc, x.StartTime)
	servicetwill_enc_slice_Team_8cac63b4(enc, x.Teams)
}

func (x *SportsEvent) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("SportsEvent.WeaverUnmarshal: nil receiver"))
	}
	x.Event = servicetwill_dec_ptr_Event_e8a4a956(dec)
	x.League = dec.String()
	x.GameID = dec.String()
	x.StartTime = servicetwill_dec_ptr_Time_7d81a94d(dec)
	x.Teams = servicetwill_dec_slice_Team_8cac63b4(dec)
}

func servicetwill_enc_ptr_Event_e8a4a956(enc *codegen.Encoder, arg *types.Event) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func servicetwill_dec_ptr_Event_e8a4a956(dec *codegen.Decoder) *types.Event {
	if !dec.Bool() {
		return nil
	}
	var res types.Event
	(&res).WeaverUnmarshal(dec)
	return &res
}

func servicetwill_enc_ptr_Time_7d81a94d(enc *codegen.Encoder, arg *time.Time) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeBinaryMarshaler(arg)
	}
}

func servicetwill_dec_ptr_Time_7d81a94d(dec *codegen.Decoder) *time.Time {
	if !dec.Bool() {
		return nil
	}
	var res time.Time
	dec.DecodeBinaryUnmarshaler(&res)
	return &res
}

func servicetwill_enc_slice_Team_8cac63b4(enc *codegen.Encoder, arg []Team) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for i := 0; i < len(arg); i++ {
		(arg[i]).WeaverMarshal(enc)
	}
}

func servicetwill_dec_slice_Team_8cac63b4(dec *codegen.Decoder) []Team {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make([]Team, n)
	for i := 0; i < n; i++ {
		(&res[i]).WeaverUnmarshal(dec)
	}
	return res
}

var _ codegen.AutoMarshal = (*Team)(nil)

type __is_Team[T ~struct {
	twill.AutoMarshal
	Name         string "json:\"name\""
	Abbreviation string "json:\"abbreviation,omitempty\""
	Role         string "json:\"role,omitempty\""
}] struct{}

var _ __is_Team[Team]

func (x *Team) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Team.WeaverMarshal: nil receiver"))
	}
	enc.String(x.Name)
	enc.String(x.Abbreviation)
	enc.String(x.Role)
}

func (x *Team) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Team.WeaverUnmarshal: nil receiver"))
	}
	x.Name = dec.String()
	x.Abbreviation = dec.String()
	x.Role = dec.String()
}

// Encoding/decoding implementations.

func servicetwill_enc_ptr_SportsEvent_93a527b6(enc *codegen.Encoder, arg *SportsEvent) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func servicetwill_dec_ptr_SportsEvent_93a527b6(dec *codegen.Decoder) *SportsEvent {
	if !dec.Bool() {
		return nil
	}
	var res SportsEvent
	(&res).WeaverUnmarshal(dec)
	return &res
}

func servicetwill_enc_ptr_EventFilters_e36df6d3(enc *codegen.Encoder, arg *EventFilters) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func servicetwill_dec_ptr_EventFilters_e36df6d3(dec *codegen.Decoder) *EventFilters {
	if !dec.Bool() {
		return nil
	}
	var res EventFilters
	(&res).WeaverUnmarshal(dec)
	return &res
}

func servicetwill_enc_slice_ptr_SportsEvent_61fee747(enc *codegen.Encoder, arg []*SportsEvent) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for i := 0; i < len(arg); i++ {
		servicetwill_enc_ptr_SportsEvent_93a527b6(enc, arg[i])
	}
}

func servicetwill_dec_slice_ptr_SportsEvent_61fee747(dec *codegen.Decoder) []*SportsEvent {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make([]*SportsEvent, n)
	for i := 0; i < n; i++ {
		res[i] = servicetwill_dec_ptr_SportsEvent_93a527b6(dec)
	}
	return res
}

// Size implementations.

// servicetwill_size_ptr_EventFilters_e36df6d3 returns the size (in bytes) of the serialization
// of the provided type.
func servicetwill_size_ptr_EventFilters_e36df6d3(x *EventFilters) int {
	if x == nil {
		return 1
	} else {
		return 1 + servicetwill_size_EventFilters_896098c2(&*x)
	}
}

// servicetwill_size_EventFilters_896098c2 returns the size (in bytes) of the serialization
// of the provided type.
func servicetwill_size_EventFilters_896098c2(x *EventFilters) int {
	size := 0
	size += 0
	size += (4 + len(x.League))
	size += (4 + len(x.Team))
	size += (4 + len(x.Status))
	size += 8
	size += 8
	return size
}
